### ISSUE TITLE
BUG: cockroachdb not showing all tables in table list

### ISSUE THREAD

**Issue by bladefist** [beekeeper-studio/beekeeper-studio#1177]
**Describe the bug**
Once connected to a cockroach cluster, I'm not seeing all the tables of my database.  When I login, zero show, if I switch to another database and switch back, a few appear.  Some of my other databases in the same cluster are showing all my tables fine.

**Expected behavior**
Show all tables

**Version Information (please complete the following information):**
 - OS: Windows 10
 - App Version 3.4.1
 - Database type cockroachdb

**Additional context**
If you guys can share what sql query you're running to get the tables I'd be happy to help troubleshoot.  I normally use TablePlus and it works fine with cockroach. Love your product though and am eager to switch!

**Comment by rathboma** [comment]
Hey! Are you using cockroach cloud by any chance?

**Comment by rathboma** [comment]
Can you check the developer tools for any errors? help -> show developer tools

**Comment by bladefist** [comment]
```vue.runtime.esm.js:1897 error: cannot determine type of empty array. Consider annotating with the desired type, for example ARRAY[]:::int[]
    at h.parseErrorMessage (app://./js/chunk-vendors.1d55ef3c.js:54:348148)
    at handlePacket (app://./js/chunk-vendors.1d55ef3c.js:54:344788)
    at h.parse (app://./js/chunk-vendors.1d55ef3c.js:54:343434)
    at TLSSocket.<anonymous> (app://./js/chunk-vendors.1d55ef3c.js:139:36915)
    at TLSSocket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at TLSSocket.Readable.push (internal/streams/readable.js:223:10)
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:188:23)```

**Comment by bladefist** [comment]
No sir.
