### ISSUE TITLE
BUG: Context Menu - SQL Create is Not Working (Redshift)

### ISSUE THREAD

**Issue by jeffcap1** [beekeeper-studio/beekeeper-studio#1316]
**Describe the bug**
I'm connected to a Redshift database and when I right click on a table to bring up the context menu and click "SQL: Create" nothing happens. Bringing up the Developer Tools in BeekeeperStudio I see the following error.

```
vue.runtime.esm.js:1897 error: syntax error at or near "identity"
    at h.parseErrorMessage (app://./js/chunk-vendors.d7d1a4fa.js:54:386941)
    at handlePacket (app://./js/chunk-vendors.d7d1a4fa.js:54:383581)
    at h.parse (app://./js/chunk-vendors.d7d1a4fa.js:54:382227)
    at Socket.<anonymous> (app://./js/chunk-vendors.d7d1a4fa.js:139:35522)
    at Socket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
```

**To Reproduce**
1. Connect to a Redshift Database
2. Right Click on a Table
3. Click "SQL: Create"
4. Nothing will happen
5. Open the Developer Tools and change to the console view
6. Try clicking "SQL: Create" again and you will see the error

**Expected behavior**
A new query window will open providing the SQL to re-create the table.

**Screenshots / Gifs**
Menu
<img width="173" alt="image" src="https://user-images.githubusercontent.com/7104326/181261674-f230634e-976d-4167-b2d8-bfdcfda002d7.png">

Error
<img width="539" alt="image" src="https://user-images.githubusercontent.com/7104326/181261027-2405869f-9711-4fd7-b024-4f9619167b30.png">

**Version Information (please complete the following information):**
 - OS: Mac v12.4
 - App Version 3.6.2
 - PostgreSQL 8.0.2 (Redshift 1.0.40182)

**Comment by rathboma** [comment]
@jeffcap1 Is this for all tables, or just for some of them? I haven't seen this with my PSQL database, so thinking that it is redshift specific.

Can you give me an example table creation schema to test this with?

**Comment by jeffcap1** [comment]
Hey @rathboma, yes you are correct this is not an issue for me with Postgres, it just seems to happen with Redshift. Looks like it's happening for both tables and views.

Here is something to test with, let me know if this helps.

```
create table if not exists test_product
(
  id bigint not null,
  name                  varchar(200),
  price                 numeric(20, 4) encode az64,
);

alter table test_product owner to "USERNAME";

grant delete, insert, select, update on test_product to "USERNAME";
```

**Comment by rathboma** [comment]
Is this still a problem? Not sure. Either way we can investigate to check.

**Comment by jeffcap1** [comment]
> Is this still a problem? Not sure. Either way we can investigate to check.

@rathboma, yep I just tried this again and unfortunately I am still receiving the same `identity` error when right clicking on a Redshift Table or View and using the `SQL: Create` option.
