### ISSUE TITLE
Debian 10 incompatibility 

### ISSUE THREAD

**Issue by farnas123** [beekeeper-studio/beekeeper-studio#158]
Hello! It doesn't work under Debian 10 (64 bit) at all even I can install it using Ubuntu instruction, Snap or AppImage. Could you please fix it and make it functional under Debian 10 and maybe other Debian based distribution as well but not only Ubuntu. Thanks in advance!

**Comment by mattzuba** [comment]
I ran into the same issue.  [This issue on electron/electron](https://github.com/electron/electron/issues/17972) helped as a workaround.

**Comment by gersh0m** [comment]
No luck for me. Just freezes with this error message:
```
Fontconfig warning: "/etc/fonts/fonts.conf", line 100: unknown element "blank"
db-connection
13:17:12.997                  › initializing background
13:17:13.002                  › initializing user ORM connection
13:17:13.003                  › registering schema
13:17:13.090                  › Creating first window
13:17:13.099                  › UnhandledRejection DriverPackageNotInstalledError: SQLite package has not been found installed. Try to install it: npm install better-sqlite3 --save
    at process.n (/opt/Beekeeper Studio/resources/app.asar/background.js:2:303632)
    at process.emit (events.js:315:20)
    at processPromiseRejections (internal/process/promises.js:245:33)
    at processTicksAndRejections (internal/process/task_queues.js:94:32)
```

Installed on Debian 10 following the 'system' instruction (by apt)

**Comment by rathboma** [comment]
@gersh0m Yes there are multiple issues with Buster right now, including the Sqlite driver not loading. I recommend using the `snap` for now.

**Comment by rathboma** [comment]
Once this build completes, try using it - https://github.com/beekeeper-studio/beekeeper-studio/actions/runs/875473732

use with `--no-sandbox` should be automatic now too, so you don't need to specify that.

**Comment by gersh0m** [comment]
It worked!... I tried the 'apt' version.
Thanx!
