### ISSUE TITLE
BUG: Say something here

### ISSUE THREAD

**Issue by lexx9999** [beekeeper-studio/beekeeper-studio#1609]
**Describe the bug**
"SQL: Create" fails on a sqlite table when tablename is quoted in brackets.

**To Reproduce**
1. create a table like 
`CREATE TABLE [test] (day timestamp not null);
`
2. right click on table -> "SQL: CREATE"
nothing happens (except an error in console)
```
vue.runtime.esm.js:3019 Error: Parse error: Unexpected "[test] (da" at line 1 column 14
    at e.value (TokenizerEngine.js:88:14)
    at e.value (TokenizerEngine.js:68:24)
    at e.value (Tokenizer.js:66:59)
    at e.tokenize (createParser.js:38:95)
    at e.value (LexerAdapter.js:38:26)
    at o.feed (nearley.js:281:15)
    at Object.parse (createParser.js:48:33)
    at n.value (Formatter.js:93:70)
    at n.value (Formatter.js:85:22)
    at U (sqlFormatter.js:127:36)

```
**Expected behavior**
Create statement shown.

**Version Information (please complete the following information):**
 - OS: Win 10
 - App Version 3.9.14
 - Database type and version  sqlite 3.41.0

**Additional context**
docs: https://sqlite.org/lang_keywords.html
Using any other quoting style works, just square brackets fails.
Since brackets are [sqlserver ](https://learn.microsoft.com/en-us/sql/relational-databases/databases/database-identifiers?view=sql-server-ver16) extension, the problem might appear there also, but I didn't check that.
Note: Low prio for me, just to let you know.

**Comment by davidkaufman** [comment]
Thanks @lexx9999 I am seeing the same error.  If I create the table with single-quotes, double-quotes or backticks around the table name, then the `SQL: Create` menu works, but if i use square brackets around the table name when creating the table, it throws that error.

I'll look into it!

**Comment by rathboma** [comment]
<img width="948" alt="Screen Shot 2023-06-08 at 6 18 13 PM" src="https://github.com/beekeeper-studio/beekeeper-studio/assets/279769/6a6f787b-401f-4ee0-b90d-bfa48598f2d5">

@davidkaufman also see from postgres user in the chat

**Comment by davidkaufman** [comment]
Ok thanks to @not-night-but's help, I was able to fix this by reviewing their fix for 

- #1599

where they bypassed the `format()` call in `loadRoutineCreate()`:

```diff
git show b6b57897
--- a/apps/studio/src/components/CoreTabs.vue
+++ b/apps/studio/src/components/CoreTabs.vue
@@ -445,8 +445,8 @@ export default Vue.extend({
     },
     async loadRoutineCreate(routine) {
       const result = await this.connection.getRoutineCreateScript(routine.name, routine.type, routine.schema)
-      const stringResult = format(_.isArray(result) ? result[0] : result, { language: FormatterDialect(this.dialect) })
-      this.createQuery(stringResult)
+      // const stringResult = format(_.isArray(result) ? result[0] : result, { language: FormatterDialect(this.dialect) })
+      this.createQuery(_.isArray(result) ? result[0] : result);
     },
     openTableBuilder() {
       const tab = new OpenTab('table-builder')
``` 

and applying that same fix to the `loadRoutineCreate()` method as well:

```diff
--- a/apps/studio/src/components/CoreTabs.vue
+++ b/apps/studio/src/components/CoreTabs.vue
@@ -410,22 +410,21 @@ export default Vue.extend({
     async loadTableCreate(table) {
       let method = null
       if (table.entityType === 'table') method = this.connection.getTableCreateScript
       else if (table.entityType === 'view') method = this.connection.getViewCreateScript
       else if (table.entityType === 'materialized-view') method = this.connection.getMaterializedViewCreateScript
       if (!method) {
         this.$noty.error(`Can't find script for ${table.name} (${table.entityType})`)
         return
       }
       const result = await method(table.name, table.schema)
-      const stringResult = format(_.isArray(result) ? result[0] : result, { language: FormatterDialect(this.dialect) })
-      this.createQuery(stringResult)
+      this.createQuery(_.isArray(result) ? result[0] : result)
     },
     dropDatabaseElement({ item: dbActionParams, action: dbAction }) {
       this.dbElement = dbActionParams.name
       this.dbAction = dbAction
       this.dbEntityType = dbActionParams.entityType
```

Now testing duplicate table which calls `format()` the "old way" too...

**Comment by davidkaufman** [comment]
ok duplicateTableSql() wasn't affected because it didn't use sqlite3's `.schema()` call which weirdly returns the create statement _exactly as originally executed_ (in this case, with the square-bracket delimiters that `format()` chokes on).  I have no idea why sqlite3 "remembers" and regurgitates the exact create table command -- down to the whitespace -- that was used, instead of recreating a new, strictly legal "canonical" `create table` command (like frinstance MySQL does)

But this should be good now.  I'll get back to trying to recreate #1612 now, to see if this fixes that too

**Comment by davidkaufman** [comment]
Creating a regression test for this (and #162) so at least we'll know if future `sql-formatter` upgrades break this stuff again

**Comment by not-night-but** [comment]
@davidkaufman Have you tried downgrading/upgrading the library to see if maybe this was a regression on their end? Their repo only really says that they don't support stored procs and changing the delimiter to something other than `;`

**Comment by davidkaufman** [comment]
No I just copied your fix to loadRoutineCreate() since @lexx9999 reported this was previously working and had recently stopped

**Comment by davidkaufman** [comment]
Actually no @lexx9999 didnt say that I misremembered

**Comment by davidkaufman** [comment]
I'll try the rollback to see if it was a long-standing or recent regression

**Comment by not-night-but** [comment]
@davidkaufman I updated the library in that same PR, so it may just be some weird issue with it. I believe we were on version 6 or something and I upgraded to 11. Could go up to 13 but I was getting some compilation issues with the latest version.
