### ISSUE TITLE
Failure building Beekeeper 1.4.1 macOS Electron app

### ISSUE THREAD

**Issue by herbygillot** [beekeeper-studio/beekeeper-studio#170]
Pertinent error: `beekeeper-studio-beekeeper-studio-2f92599/src/main.js: Cannot find module '@babel/compat-data/corejs3-shipped-proposals'`

Full error:
```
yarn run v1.22.4
$ vue-cli-service electron:build --mac dir
 INFO  Bundling render process:

-  Building modern bundle for production...
 WARN  A new version of sass-loader is available. Please upgrade for best experience.
 ERROR  Failed to compile with 1 errors2:11:26 PM

 error  in ./src/main.js

Module build failed (from ./node_modules/thread-loader/dist/cjs.js):
Thread Loader (Worker 0)
[BABEL] /opt/macports-test/var/macports/build/_Users_herby_Source_macports-ports_aqua_beekeeper-studio/beekeeper-studio/work/beekeeper-studio-beekeeper-studio-2f92599/src/main.js: Cannot find module '@babel/compat-data/corejs3-shipped-proposals'
Require stack:
- /opt/macports-test/var/macports/build/_Users_herby_Source_macports-ports_aqua_beekeeper-studio/beekeeper-studio/work/beekeeper-studio-beekeeper-studio-2f92599/node_modules/@babel/preset-env/lib/polyfills/corejs3/usage-plugin.js
- /opt/macports-test/var/macports/build/_Users_herby_Source_macports-ports_aqua_beekeeper-studio/beekeeper-studio/work/beekeeper-studio-beekeeper-studio-2f92599/node_modules/@babel/preset-env/lib/index.js
- /opt/macports-test/var/macports/build/_Users_herby_Source_macports-ports_aqua_beekeeper-studio/beekeeper-studio/work/beekeeper-studio-beekeeper-studio-2f92599/node_modules/@vue/babel-preset-app/index.js
- /opt/macports-test/var/macports/build/_Users_herby_Source_macports-ports_aqua_beekeeper-studio/beekeeper-studio/work/beekeeper-studio-beekeeper-studio-2f92599/node_modules/@vue/cli-plugin-babel/preset.js
- /opt/macports-test/var/macports/build/_Users_herby_Source_macports-ports_aqua_beekeeper-studio/beekeeper-studio/work/beekeeper-studio-beekeeper-studio-2f92599/node_modules/@babel/core/lib/config/files/plugins.js
- /opt/macports-test/var/macports/build/_Users_herby_Source_macports-ports_aqua_beekeeper-studio/beekeeper-studio/work/beekeeper-studio-beekeeper-studio-2f92599/node_modules/@babel/core/lib/config/files/index.js
- /opt/macports-test/var/macports/build/_Users_herby_Source_macports-ports_aqua_beekeeper-studio/beekeeper-studio/work/beekeeper-studio-beekeeper-studio-2f92599/node_modules/@babel/core/lib/index.js
- /opt/macports-test/var/macports/build/_Users_herby_Source_macports-ports_aqua_beekeeper-studio/beekeeper-studio/work/beekeeper-studio-beekeeper-studio-2f92599/node_modules/babel-loader/lib/index.js
- /opt/macports-test/var/macports/build/_Users_herby_Source_macports-ports_aqua_beekeeper-studio/beekeeper-studio/work/beekeeper-studio-beekeeper-studio-2f92599/node_modules/loader-runner/lib/loadLoader.js
- /opt/macports-test/var/macports/build/_Users_herby_Source_macports-ports_aqua_beekeeper-studio/beekeeper-studio/work/beekeeper-studio-beekeeper-studio-2f92599/node_modules/loader-runner/lib/LoaderRunner.js
- /opt/macports-test/var/macports/build/_Users_herby_Source_macports-ports_aqua_beekeeper-studio/beekeeper-studio/work/beekeeper-studio-beekeeper-studio-2f92599/node_modules/thread-loader/dist/worker.js (While processing: "/opt/macports-test/var/macports
/build/_Users_herby_Source_macports-ports_aqua_beekeeper-studio/beekeeper-studio/work/beekeeper-studio-beekeeper-studio-2f92599/node_modules/@vue/cli-plugin-babel/preset.js")
    at PoolWorker.fromErrorObj (/opt/macports-test/var/macports/build/_Users_herby_Source_macports-ports_aqua_beekeeper-studio/beekeeper-studio/work/beekeeper-studio-beekeeper-studio-2f92599/node_modules/thread-loader/dist/WorkerPool.js:262:12)
    at /opt/macports-test/var/macports/build/_Users_herby_Source_macports-ports_aqua_beekeeper-studio/beekeeper-studio/work/beekeeper-studio-beekeeper-studio-2f92599/node_modules/thread-loader/dist/WorkerPool.js:204:29
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:966:15)
    at Function.Module._load (internal/modules/cjs/loader.js:842:27)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/opt/macports-test/var/macports/build/_Users_herby_Source_macports-ports_aqua_beekeeper-studio/beekeeper-studio/work/beekeeper-studio-beekeeper-studio-2f92599/node_modules/@babel/preset-env/lib/polyfills/corejs3/usage-plugin.js
:10:55)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Module.require (internal/modules/cjs/loader.js:1026:19)

 @ multi ./src/main.js

 ERROR  Vue CLI build failed. Please resolve any issues with your build and try again.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Command failed: CSC_IDENTITY_AUTO_DISCOVERY=false yarn run electron:build --mac dir
```

macOS `10.15.5`
yarn `1.22.4`
node `12.17.0`

**Comment by rathboma** [comment]
I think this is an issue with newer versions of node and some of the Babel plugins.

Let me look tomorrow. But in the meantime, downgrading to node 10, or maybe 12.16.2

**Comment by herbygillot** [comment]
I think we are now good here. Closing.
