### ISSUE TITLE
BUG: Say something here

### ISSUE THREAD

**Issue by w473** [beekeeper-studio/beekeeper-studio#1727]
**Describe the bug**
Empty page on every "View Data" or "View Structure" in console:

`TabWithTable.vue?8011:9 table changed
parser.js:287 Uncaught (in promise) error: more than one row returned by a subquery used as an expression
    at h.parseErrorMessage (app://./js/chunk-vendors.0325aab3.js:129:47652)
    at handlePacket (app://./js/chunk-vendors.0325aab3.js:129:44292)
    at h.parse (app://./js/chunk-vendors.0325aab3.js:129:42938)
    at Socket.<anonymous> (app://./js/chunk-vendors.0325aab3.js:303:54421)
    at Socket.emit (node:events:390:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:199:23)`

**To Reproduce**
1. Go to "View Data" or "View Structure"

**Expected behavior**
See the data from tables

**Version Information (please complete the following information):**
 - OS: MACOS Ventura 13.5.2 (22G91)
 - App Version 4
 - Database type and version Postgres 13.8

**Additional context**
Running just query will show data correctly

**Comment by wmontgomery** [comment]
@w473 Are you able to share the schema you're using and a rows counts you expect in those tables? Trying to reproduce on Macos Sonoma (14) and postgres 13 also.

**Comment by w473** [comment]
CREATE TABLE
  public.review (
    id serial NOT NULL,
    tenant "tenant-enum" NOT NULL,
    "partnerId" text NULL,
    "productId" text NOT NULL,
    "createdAt" timestamp with time zone NOT NULL,
    "updatedAt" timestamp with time zone NOT NULL,
    customer jsonb NOT NULL,
    title character varying NOT NULL,
    content character varying NOT NULL,
    status character varying NOT NULL,
    "syncStatus" character varying NOT NULL,
    "imageUrl" text NULL,
    comment text NULL,
      rating integer NOT NULL,
      "votesUp" integer NOT NULL,
      "votesDown" integer NOT NULL,
      "locationId" text NULL
  );

ALTER TABLE
  public.review
ADD
  CONSTRAINT "PK_1" PRIMARY KEY (id)


ALTER TABLE "review" ADD CONSTRAINT "FK_2" FOREIGN KEY ("productId") REFERENCES "product"("productId") ON DELETE CASCADE ON UPDATE NO ACTION;

ALTER TABLE "review" ADD CONSTRAINT "FK_3" FOREIGN KEY ("locationId", "productId") REFERENCES "location"("locationId","productId") ON DELETE CASCADE ON UPDATE NO ACTION;

**Comment by rathboma** [comment]
Closing this as I think we've fixed it
