### ISSUE TITLE
Doesn't work in my shell - rc

### ISSUE THREAD

**Issue by lawless-m** [beekeeper-studio/beekeeper-studio#177]
Hi,

this one is a puzzler

If I start the AppImage version under bash or ksh everything is fine. If I use my normal shell - Tom Duff's rc shell - http://doc.cat-v.org/plan_9/4th_edition/papers/rc - which is part of plan9ports

then it just sits at the loading screen bouncing the yellow disks.

**Comment by rathboma** [comment]
My guess is that there are some missing environment variables or something, try running like:

DEBUG=* beekeeper-studio and see if you can find a definite error to paste here?

**Comment by lawless-m** [comment]
matt@hex:~$ rc
% DEBUG=* Beekeeper-Studio-1.4.1.AppImage
LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:
0=/dev/stdin
LANG=en_GB.UTF-8
GDM_LANG=en_GB.utf8
DISPLAY=:0
OLDPWD=/home/matt/.ssh
APPIMAGE=/home/matt/bin/Beekeeper-Studio-1.4.1.AppImage
GTK_OVERLAY_SCROLLING=0
DEBUG=*
COLORTERM=truecolor
XDG_VTNR=7
SSH_AUTH_SOCK=/run/user/1000/keyring/ssh
XDG_SESSION_ID=1
XDG_GREETER_DATA_DIR=/var/lib/lightdm/data/matt
USER=matt
DESKTOP_SESSION=lightdm-xsession
status=false
QT_QPA_PLATFORMTHEME=gtk2
PWD=/home/matt
ifs= 	

HOME=/home/matt
SSH_AGENT_PID=1168
QT_ACCESSIBILITY=1
pid=5167
XDG_SESSION_TYPE=x11
prompt=% 	
XDG_DATA_DIRS=/usr/share/gnome:/usr/local/share/:/usr/share/
XDG_SESSION_DESKTOP=lightdm-xsession
GJS_DEBUG_OUTPUT=stderr
ARGV0=Beekeeper-Studio-1.4.1.AppImage
GTK_MODULES=gail:atk-bridge
home=/home/matt
VTE_VERSION=4601
TERM=xterm-256color
SHELL=/bin/bash
XDG_SEAT_PATH=/org/freedesktop/DisplayManager/Seat0
XDG_CURRENT_DESKTOP=X-Cinnamon
GPG_AGENT_INFO=/run/user/1000/gnupg/S.gpg-agent:0:1
QT_LINUX_ACCESSIBILITY_ALWAYS_ON=1
XDG_SEAT=seat0
SHLVL=2
LANGUAGE=en_GB:en
rcname=rc
PLAN9=/opt/plan9port
WINDOWID=62914791
GDMSESSION=lightdm-xsession
APPDIR=/tmp/.mount_BeekeefY99Qa
GNOME_DESKTOP_SESSION_ID=this-is-deprecated
LOGNAME=matt
DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
XDG_RUNTIME_DIR=/run/user/1000
XAUTHORITY=/home/matt/.Xauthority
XDG_SESSION_PATH=/org/freedesktop/DisplayManager/Session0
path=/opt/plan9port/bin/usr/local/bin/usr/bin/bin/usr/local/games/usr/games/home/matt/bin/opt/plan9port/bin.
PATH=/opt/plan9port/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/home/matt/bin:/opt/plan9port/bin:
CINNAMON_VERSION=3.2.7
GJS_DEBUG_TOPICS=JS ERROR;JS LOG
SESSION_MANAGER=local/hex:@/tmp/.ICE-unix/1116,unix/hex:/tmp/.ICE-unix/1116
OWD=/home/matt
_=/usr/bin/env
+ THIS=/tmp/.mount_BeekeefY99Qa/AppRun
+ args=("$@")
+ NUMBER_OF_ARGS=0
+ '[' -z /tmp/.mount_BeekeefY99Qa ']'
+ export PATH=/tmp/.mount_BeekeefY99Qa:/tmp/.mount_BeekeefY99Qa/usr/sbin:/opt/plan9port/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/home/matt/bin:/opt/plan9port/bin:
+ PATH=/tmp/.mount_BeekeefY99Qa:/tmp/.mount_BeekeefY99Qa/usr/sbin:/opt/plan9port/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/home/matt/bin:/opt/plan9port/bin:
+ export XDG_DATA_DIRS=./share/:/usr/share/gnome:/usr/local/share/:/usr/share/:/usr/share/gnome:/usr/local/share/:/usr/share/
+ XDG_DATA_DIRS=./share/:/usr/share/gnome:/usr/local/share/:/usr/share/:/usr/share/gnome:/usr/local/share/:/usr/share/
+ export LD_LIBRARY_PATH=/tmp/.mount_BeekeefY99Qa/usr/lib:
+ LD_LIBRARY_PATH=/tmp/.mount_BeekeefY99Qa/usr/lib:
+ export XDG_DATA_DIRS=/tmp/.mount_BeekeefY99Qa/usr/share/:./share/:/usr/share/gnome:/usr/local/share/:/usr/share/:/usr/share/gnome:/usr/local/share/:/usr/share/:/usr/share/gnome/:/usr/local/share/:/usr/share/
+ XDG_DATA_DIRS=/tmp/.mount_BeekeefY99Qa/usr/share/:./share/:/usr/share/gnome:/usr/local/share/:/usr/share/:/usr/share/gnome:/usr/local/share/:/usr/share/:/usr/share/gnome/:/usr/local/share/:/usr/share/
+ export GSETTINGS_SCHEMA_DIR=/tmp/.mount_BeekeefY99Qa/usr/share/glib-2.0/schemas:
+ GSETTINGS_SCHEMA_DIR=/tmp/.mount_BeekeefY99Qa/usr/share/glib-2.0/schemas:
+ BIN=/tmp/.mount_BeekeefY99Qa/beekeeper-studio
+ '[' -z '' ']'
+ trap atexit EXIT
+ isEulaAccepted=1
+ '[' -z /home/matt/bin/Beekeeper-Studio-1.4.1.AppImage ']'
+ atexit
+ '[' 1 == 1 ']'
+ '[' 0 -eq 0 ']'
+ exec /tmp/.mount_BeekeefY99Qa/beekeeper-studio
Fontconfig warning: "/etc/fonts/fonts.conf", line 100: unknown element "blank"
Not running in AppImageLauncher
{
  LD_LIBRARY_PATH: '/tmp/.mount_BeekeefY99Qa/usr/lib:',
  LS_COLORS: 'rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:',
  '0': undefined,
  LANG: 'en_GB.UTF-8',
  GDM_LANG: 'en_GB.utf8',
  DISPLAY: ':0',
  OLDPWD: '/home/matt/.ssh',
  APPIMAGE: '/home/matt/bin/Beekeeper-Studio-1.4.1.AppImage',
  GTK_OVERLAY_SCROLLING: '0',
  DEBUG: '\u0001*',
  COLORTERM: 'truecolor',
  XDG_VTNR: '7',
  SSH_AUTH_SOCK: '/run/user/1000/keyring/ssh',
  XDG_SESSION_ID: '1',
  XDG_GREETER_DATA_DIR: '/var/lib/lightdm/data/matt',
  USER: 'matt',
  DESKTOP_SESSION: 'lightdm-xsession',
  status: 'false',
  QT_QPA_PLATFORMTHEME: 'gtk2',
  PWD: '/home/matt',
  ifs: ' \t\n',
  HOME: '/home/matt',
  SSH_AGENT_PID: '1168',
  QT_ACCESSIBILITY: '1',
  pid: '5167',
  XDG_SESSION_TYPE: 'x11',
  prompt: '% \u0001\t',
  XDG_DATA_DIRS: '/tmp/.mount_BeekeefY99Qa/usr/share/:./share/:/usr/share/gnome:/usr/local/share/:/usr/share/:/usr/share/gnome:/usr/local/share/:/usr/share/:/usr/share/gnome/:/usr/local/share/:/usr/share/',
  GSETTINGS_SCHEMA_DIR: '/tmp/.mount_BeekeefY99Qa/usr/share/glib-2.0/schemas:',
  XDG_SESSION_DESKTOP: 'lightdm-xsession',
  GJS_DEBUG_OUTPUT: 'stderr',
  ARGV0: 'Beekeeper-Studio-1.4.1.AppImage',
  GTK_MODULES: 'gail:atk-bridge',
  home: '/home/matt',
  VTE_VERSION: '4601',
  TERM: 'xterm-256color',
  SHELL: '/bin/bash',
  XDG_SEAT_PATH: '/org/freedesktop/DisplayManager/Seat0',
  XDG_CURRENT_DESKTOP: 'X-Cinnamon',
  GPG_AGENT_INFO: '/run/user/1000/gnupg/S.gpg-agent:0:1',
  QT_LINUX_ACCESSIBILITY_ALWAYS_ON: '1',
  XDG_SEAT: 'seat0',
  SHLVL: '1',
  LANGUAGE: 'en_GB:en',
  rcname: 'rc',
  PLAN9: '/opt/plan9port',
  WINDOWID: '62914791',
  GDMSESSION: 'lightdm-xsession',
  APPDIR: '/tmp/.mount_BeekeefY99Qa',
  GNOME_DESKTOP_SESSION_ID: 'this-is-deprecated',
  LOGNAME: 'matt',
  DBUS_SESSION_BUS_ADDRESS: 'unix:path=/run/user/1000/bus',
  XDG_RUNTIME_DIR: '/run/user/1000',
  XAUTHORITY: '/home/matt/.Xauthority',
  XDG_SESSION_PATH: '/org/freedesktop/DisplayManager/Session0',
  path: '/opt/plan9port/bin\u0001/usr/local/bin\u0001/usr/bin\u0001/bin\u0001/usr/local/games\u0001/usr/games\u0001/home/matt/bin\u0001/opt/plan9port/bin\u0001.',
  PATH: '/tmp/.mount_BeekeefY99Qa:/tmp/.mount_BeekeefY99Qa/usr/sbin:/opt/plan9port/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/home/matt/bin:/opt/plan9port/bin:',
  CINNAMON_VERSION: '3.2.7',
  GJS_DEBUG_TOPICS: 'JS ERROR;JS LOG',
  SESSION_MANAGER: 'local/hex:@/tmp/.ICE-unix/1116,unix/hex:/tmp/.ICE-unix/1116',
  OWD: '/home/matt',
  NO_AT_BRIDGE: '1',
  CHROME_DESKTOP: 'beekeeper-studio.desktop'
}
Failed to register app protocol Error: Invalid package /tmp/.mount_BeekeefY99Qa/resources/app.asar/tmp/.mount_BeekeefY99Qa/resources/electron.asar
    at createError (electron/js2c/asar.js:124:17)
    at fs.readFile (electron/js2c/asar.js:539:23)
    at Function.<anonymous> (/tmp/.mount_BeekeefY99Qa/resources/app.asar/background.js:2:513329)



this last error message (Failed to register....)  is then repeated another 280 times

**Comment by rathboma** [comment]
@lawless-m can you dload one of the linux builds here - https://github.com/beekeeper-studio/beekeeper-studio/actions/runs/132290778 and test the app image? I've had to replace the regular executable with a bash script (for another issue) in linux, so this may fix your problem

**Comment by lawless-m** [comment]
I used ubuntu-18.04

matt@hex:/dev/shm$ rc
% DEBUG=* ./B*
LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:
0=/dev/stdin
LANG=en_GB.UTF-8
GDM_LANG=en_GB.utf8
DISPLAY=:0
OLDPWD=/home/matt
APPIMAGE=/dev/shm/Beekeeper Studio-1.4.1.AppImage
GTK_OVERLAY_SCROLLING=0
DEBUG=*
COLORTERM=truecolor
XDG_VTNR=7
SSH_AUTH_SOCK=/run/user/1000/keyring/ssh
XDG_SESSION_ID=1
XDG_GREETER_DATA_DIR=/var/lib/lightdm/data/matt
USER=matt
DESKTOP_SESSION=lightdm-xsession
status=false
QT_QPA_PLATFORMTHEME=gtk2
PWD=/dev/shm
ifs= 	

HOME=/home/matt
SSH_AGENT_PID=1168
QT_ACCESSIBILITY=1
pid=20775
XDG_SESSION_TYPE=x11
prompt=% 	
XDG_DATA_DIRS=/usr/share/gnome:/usr/local/share/:/usr/share/
XDG_SESSION_DESKTOP=lightdm-xsession
GJS_DEBUG_OUTPUT=stderr
ARGV0=./Beekeeper Studio-1.4.1.AppImage
GTK_MODULES=gail:atk-bridge
home=/home/matt
VTE_VERSION=4601
TERM=xterm-256color
SHELL=/bin/bash
XDG_SEAT_PATH=/org/freedesktop/DisplayManager/Seat0
XDG_CURRENT_DESKTOP=X-Cinnamon
GPG_AGENT_INFO=/run/user/1000/gnupg/S.gpg-agent:0:1
QT_LINUX_ACCESSIBILITY_ALWAYS_ON=1
XDG_SEAT=seat0
SHLVL=2
LANGUAGE=en_GB:en
rcname=rc
PLAN9=/opt/plan9port
WINDOWID=62914566
GDMSESSION=lightdm-xsession
APPDIR=/tmp/.mount_Beekeerg76Qv
GNOME_DESKTOP_SESSION_ID=this-is-deprecated
LOGNAME=matt
DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
XDG_RUNTIME_DIR=/run/user/1000
XAUTHORITY=/home/matt/.Xauthority
XDG_SESSION_PATH=/org/freedesktop/DisplayManager/Session0
path=/usr/local/bin/usr/bin/bin/usr/local/games/usr/games/home/matt/bin/opt/plan9port/bin.
PATH=/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/home/matt/bin:/opt/plan9port/bin:
CINNAMON_VERSION=3.2.7
GJS_DEBUG_TOPICS=JS ERROR;JS LOG
SESSION_MANAGER=local/hex:@/tmp/.ICE-unix/1116,unix/hex:/tmp/.ICE-unix/1116
OWD=/dev/shm
_=/usr/bin/env
+ THIS=/tmp/.mount_Beekeerg76Qv/AppRun
+ args=("$@")
+ NUMBER_OF_ARGS=0
+ '[' -z /tmp/.mount_Beekeerg76Qv ']'
+ export PATH=/tmp/.mount_Beekeerg76Qv:/tmp/.mount_Beekeerg76Qv/usr/sbin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/home/matt/bin:/opt/plan9port/bin:
+ PATH=/tmp/.mount_Beekeerg76Qv:/tmp/.mount_Beekeerg76Qv/usr/sbin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/home/matt/bin:/opt/plan9port/bin:
+ export XDG_DATA_DIRS=./share/:/usr/share/gnome:/usr/local/share/:/usr/share/:/usr/share/gnome:/usr/local/share/:/usr/share/
+ XDG_DATA_DIRS=./share/:/usr/share/gnome:/usr/local/share/:/usr/share/:/usr/share/gnome:/usr/local/share/:/usr/share/
+ export LD_LIBRARY_PATH=/tmp/.mount_Beekeerg76Qv/usr/lib:
+ LD_LIBRARY_PATH=/tmp/.mount_Beekeerg76Qv/usr/lib:
+ export XDG_DATA_DIRS=/tmp/.mount_Beekeerg76Qv/usr/share/:./share/:/usr/share/gnome:/usr/local/share/:/usr/share/:/usr/share/gnome:/usr/local/share/:/usr/share/:/usr/share/gnome/:/usr/local/share/:/usr/share/
+ XDG_DATA_DIRS=/tmp/.mount_Beekeerg76Qv/usr/share/:./share/:/usr/share/gnome:/usr/local/share/:/usr/share/:/usr/share/gnome:/usr/local/share/:/usr/share/:/usr/share/gnome/:/usr/local/share/:/usr/share/
+ export GSETTINGS_SCHEMA_DIR=/tmp/.mount_Beekeerg76Qv/usr/share/glib-2.0/schemas:
+ GSETTINGS_SCHEMA_DIR=/tmp/.mount_Beekeerg76Qv/usr/share/glib-2.0/schemas:
+ BIN=/tmp/.mount_Beekeerg76Qv/beekeeper-studio
+ '[' -z '' ']'
+ trap atexit EXIT
+ isEulaAccepted=1
+ '[' -z '/dev/shm/Beekeeper Studio-1.4.1.AppImage' ']'
+ atexit
+ '[' 1 == 1 ']'
+ '[' 0 -eq 0 ']'
+ exec /tmp/.mount_Beekeerg76Qv/beekeeper-studio
Fontconfig warning: "/etc/fonts/fonts.conf", line 100: unknown element "blank"
(electron) The default value of app.allowRendererProcessReuse is deprecated, it is currently "false".  It will change to be "true" in Electron 9.  For more information please check https://github.com/electron/electron/issues/18397
Not running in AppImageLauncher
{
  LS_COLORS: 'rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:',
  LD_LIBRARY_PATH: '/tmp/.mount_Beekeerg76Qv/usr/lib:',
  '0': undefined,
  LANG: 'en_GB.UTF-8',
  GDM_LANG: 'en_GB.utf8',
  DISPLAY: ':0',
  OLDPWD: '/home/matt',
  APPIMAGE: '/dev/shm/Beekeeper Studio-1.4.1.AppImage',
  GTK_OVERLAY_SCROLLING: '0',
  DEBUG: '\u0001*',
  COLORTERM: 'truecolor',
  XDG_VTNR: '7',
  SSH_AUTH_SOCK: '/run/user/1000/keyring/ssh',
  XDG_SESSION_ID: '1',
  XDG_GREETER_DATA_DIR: '/var/lib/lightdm/data/matt',
  USER: 'matt',
  DESKTOP_SESSION: 'lightdm-xsession',
  status: 'false',
  QT_QPA_PLATFORMTHEME: 'gtk2',
  PWD: '/dev/shm',
  ifs: ' \t\n',
  HOME: '/home/matt',
  SSH_AGENT_PID: '1168',
  QT_ACCESSIBILITY: '1',
  pid: '20775',
  XDG_SESSION_TYPE: 'x11',
  prompt: '% \u0001\t',
  XDG_DATA_DIRS: '/tmp/.mount_Beekeerg76Qv/usr/share/:./share/:/usr/share/gnome:/usr/local/share/:/usr/share/:/usr/share/gnome:/usr/local/share/:/usr/share/:/usr/share/gnome/:/usr/local/share/:/usr/share/',
  GSETTINGS_SCHEMA_DIR: '/tmp/.mount_Beekeerg76Qv/usr/share/glib-2.0/schemas:',
  XDG_SESSION_DESKTOP: 'lightdm-xsession',
  GJS_DEBUG_OUTPUT: 'stderr',
  ARGV0: './Beekeeper Studio-1.4.1.AppImage',
  GTK_MODULES: 'gail:atk-bridge',
  home: '/home/matt',
  SHELL: '/bin/bash',
  TERM: 'xterm-256color',
  VTE_VERSION: '4601',
  XDG_SEAT_PATH: '/org/freedesktop/DisplayManager/Seat0',
  XDG_CURRENT_DESKTOP: 'X-Cinnamon',
  GPG_AGENT_INFO: '/run/user/1000/gnupg/S.gpg-agent:0:1',
  QT_LINUX_ACCESSIBILITY_ALWAYS_ON: '1',
  SHLVL: '1',
  XDG_SEAT: 'seat0',
  LANGUAGE: 'en_GB:en',
  rcname: 'rc',
  PLAN9: '/opt/plan9port',
  WINDOWID: '62914566',
  GDMSESSION: 'lightdm-xsession',
  APPDIR: '/tmp/.mount_Beekeerg76Qv',
  GNOME_DESKTOP_SESSION_ID: 'this-is-deprecated',
  LOGNAME: 'matt',
  DBUS_SESSION_BUS_ADDRESS: 'unix:path=/run/user/1000/bus',
  XDG_RUNTIME_DIR: '/run/user/1000',
  XAUTHORITY: '/home/matt/.Xauthority',
  XDG_SESSION_PATH: '/org/freedesktop/DisplayManager/Session0',
  PATH: '/tmp/.mount_Beekeerg76Qv:/tmp/.mount_Beekeerg76Qv/usr/sbin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/home/matt/bin:/opt/plan9port/bin:',
  path: '/usr/local/bin\u0001/usr/bin\u0001/bin\u0001/usr/local/games\u0001/usr/games\u0001/home/matt/bin\u0001/opt/plan9port/bin\u0001.',
  CINNAMON_VERSION: '3.2.7',
  GJS_DEBUG_TOPICS: 'JS ERROR;JS LOG',
  SESSION_MANAGER: 'local/hex:@/tmp/.ICE-unix/1116,unix/hex:/tmp/.ICE-unix/1116',
  OWD: '/dev/shm',
  CHROME_DESKTOP: 'beekeeper-studio.desktop'
}
(node:20780) ProtocolDeprecateCallback: The callback argument of protocol module APIs is no longer needed.
(node:20780) ProtocolDeprecateCallback: The callback argument of protocol module APIs is no longer needed.

**Comment by lawless-m** [comment]
Same result. 
Again, it works fine in Bash

**Comment by lawless-m** [comment]
(with the same ProtocolDeprecateCallback message)

**Comment by lawless-m** [comment]
I do appreciate you working on this but it's not causing me any pain btw.
I already wrap it in a shell script so I just use bash

**Comment by rathboma** [comment]
I figured I'd jump in again after making the bash wrapper script to see if it fixed it, alas no.

Glad you've got a wrapper! I suspect this is some deep problem with electron's package format, and it assuming that users have a `bash` shell.
