### ISSUE TITLE
Provide a `.desktop` file in the docs for folks using the AppImage

### ISSUE THREAD

**Issue by rathboma** [beekeeper-studio/beekeeper-studio#198]
For those using the AppImage and not installing normally into their app tray it'd be nice to provide a .desktop file that points to their local copy of the app image.

A PR here should include:

1. The text of the .desktop file, along with locations to sub out the `path` of the app image
2. Instructions on where to put the .desktop file inside the user's home directory
3. Some manual testing to be sure there is an app icon

Put all of this stuff in `docs/installation/README.md` in the `Linux` section

**Comment by keith-hall** [comment]
FWIW, I personally use https://github.com/TheAssassin/AppImageLauncher to automatically manage launcher menu entries for applications bundled in AppImage format. It may be easier to recommend that in the docs instead of adding instructions for creating a `.desktop` file.

**Comment by rathboma** [comment]
I do recommend AppImageLauncher in our docs, but it is a TOTAL pita and is hard to detect for the autoupdater.

Have you received an auto-update btw? Not 100% sure it's working with the launcher.

**Comment by keith-hall** [comment]
Apologies, I admit I didn't check the docs, I just saw this issue while browsing and made the mistake of assuming you didn't know about AppImageLauncher.

I've only just started using Beekeeper Studio on Linux, but I think you're right about it not auto-updating when using AppImageLauncher. I downloaded the AppImage for Beekeeper Studio v1.6.9 and "integrated and ran it", and no auto-update occurred, and no update notification appeared anywhere. I tried restarting Beekeeper Studio a few times in case it would make a difference. Help menu -> About still shows 1.6.9 instead of the latest at the time of writing, 1.6.10.

I didn't see anything in the Web Developer Console, but in my `~/.config/beekeeper-studio/logs/main.log` file I found:

```
[2020-07-28 09:32:29.143] [info] initializing background
[2020-07-28 09:32:29.145] [info] initializing user ORM connection
[2020-07-28 09:32:29.145] [info] registering schema
[2020-07-28 09:32:29.216] [info] Creating first window
[2020-07-28 09:32:29.363] [info] running migrations
[2020-07-28 09:32:46.122] [info] getting settings
[2020-07-28 09:32:46.128] [info] setting up the menu
[2020-07-28 09:32:46.131] [info] Building the window
[2020-07-28 09:32:48.641] [info] managing updates
[2020-07-28 09:32:48.642] [info] rewriting $APPIMAGE {
  oldValue: '/run/user/1000/appimagelauncherfs/0004.AppImage',
  newValue: '/home/keith/Applications/Beekeeper-Studio-1.6.9_ffa87f38372a23dce0902d0d8efd307c.AppImage'
}
[2020-07-28 09:32:51.015] [info] Checking for update
[2020-07-28 09:32:51.031] [info] Generated new staging user ID: ec0ac7f9-9187-5469-bd3a-851427d51393
[2020-07-28 09:32:54.573] [info] Found version 1.6.10 (url: Beekeeper-Studio-1.6.10.AppImage)
[2020-07-28 09:32:54.576] [error] Error: TypeError: Cannot read property 'send' of undefined
    at /tmp/.mount_Beekee1yYqKm/resources/app.asar/background.js:2:689512
    at Array.forEach (<anonymous>)
    at p.<anonymous> (/tmp/.mount_Beekee1yYqKm/resources/app.asar/background.js:2:689487)
    at p.emit (events.js:210:5)
    at p.onUpdateAvailable (/tmp/.mount_Beekee1yYqKm/resources/app.asar/background.js:2:172788)
    at /tmp/.mount_Beekee1yYqKm/resources/app.asar/background.js:2:172466
    at Generator.next (<anonymous>)
    at n (/tmp/.mount_Beekee1yYqKm/resources/app.asar/background.js:2:11189)
    at s (/tmp/.mount_Beekee1yYqKm/resources/app.asar/background.js:2:11414)
[2020-07-28 09:32:54.576] [error] TypeError: Cannot read property 'send' of undefined
    at /tmp/.mount_Beekee1yYqKm/resources/app.asar/background.js:2:689512
    at Array.forEach (<anonymous>)
    at p.<anonymous> (/tmp/.mount_Beekee1yYqKm/resources/app.asar/background.js:2:689487)
    at p.emit (events.js:210:5)
    at p.onUpdateAvailable (/tmp/.mount_Beekee1yYqKm/resources/app.asar/background.js:2:172788)
    at /tmp/.mount_Beekee1yYqKm/resources/app.asar/background.js:2:172466
    at Generator.next (<anonymous>)
    at n (/tmp/.mount_Beekee1yYqKm/resources/app.asar/background.js:2:11189)
    at s (/tmp/.mount_Beekee1yYqKm/resources/app.asar/background.js:2:11414)
```

**Comment by mariusa** [comment]
Note, when switching windows on Linux with Alt+Tab there's no icon in the 'opened windows' display.

Maybe this is related: https://github.com/electron-userland/electron-builder/issues/4617

**Comment by rathboma** [comment]
I think this is two things:

1. I think I may have broken automatic updates in 1.6.9 for all platforms. I'm seeing this error myself.
2. Yes the icon thing is annoying on linux and is really easy to break.

**Comment by rathboma** [comment]
This is all working with AppImages integrated with AppImageLauncher
