### ISSUE TITLE
BUG: databases not loading in 4.2.5

### ISSUE THREAD

**Issue by JelleVanDerMeulen** [beekeeper-studio/beekeeper-studio#2061]
The new update 4.2.5 of 28 march has a bug. When a connection is opened the database selector is empty. This is blocking. There is a yellow animation visible. This suggests that the system is still loading information.

I use connections to mysql servers. This problem occurs on all connections. I have 9 different mysql instances including a mariaDB.

**Comment by rathboma** [comment]
OH, the databases selector is empty, no the entities..... that's weird.

**Comment by rathboma** [comment]
Please check for errors in the dev console!

**Comment by rathboma** [comment]
@PlugNPush There's nothing in the database dropdown? Can you click the 'refresh' button next to the database dropdown?

**Comment by rathboma** [comment]
Ok, this is weird. Are you connecting with an SSH tunnel or something like that?

**Comment by rathboma** [comment]
Does the loading bar ever stop? If so - does that make any errors appear in the `console` in the devtools on the right?

**Comment by PlugNPush** [comment]
I am connecting directly through localhost port 5432. The loading bar will not stop, and no errors appear in the console no matter how long I wait (just some warnings of depreciation).

**Comment by rathboma** [comment]
@PlugNPush I cannot replicate this. Let's try and figure out what is different between my environment and yours!

Some more questions:
- What version of postgresql are you using?
- Can you post a screenshot of your connection settings?
- Does this happen on EVERY connection, or just this specific database?
- What OS & architecture are you on?
- Anything else that you think could help me replicate?

**Comment by PlugNPush** [comment]
Now, for some reason as I tried again the refresh arrow made the bar stop and my databases appear... I cannot replicate it either now, it works as it was before. I am presumably on the latest version 16, I installed it today from the postgres APT repository. It was happening every time on this connection, I do not have others to test at the moment. I am on Debian 12.5 Bookworm, AMD64. Connection settings is attached below. My setup is brand new, I moved from Windows to Debian for work reasons, the installation is still fresh, not much packages installed. 
![image](https://github.com/beekeeper-studio/beekeeper-studio/assets/31410359/154afebb-d51b-46aa-bf00-0b76b115c1c2)

**Comment by rathboma** [comment]
That's really weird. If you see it again, please let me know

**Comment by PlugNPush** [comment]
I will. It started with me editing a row in a table, and it loaded for a really long time before indicating a connection timeout in red, although other softwares (like pgadmin4) had no issues accessing the database and making that edit. When I closed Beekeeper to re-open it, the issue described above began.

**Comment by JelleVanDerMeulen** [comment]
I am connecting through ssh. Dev tools doesn’t give any errors

Van: Matthew Rathbone ***@***.***>
Datum: vrijdag, 29 maart 2024 om 15:57
Aan: beekeeper-studio/beekeeper-studio ***@***.***>
CC: Jelle van der Meulen ***@***.***>, Mention ***@***.***>
Onderwerp: Re: [beekeeper-studio/beekeeper-studio] BUG: databases not loading in 4.2.5 (Issue #2061)

Does the loading bar ever stop? If so - does that make any errors appear in the console in the devtools on the right?

**Comment by PlugNPush** [comment]
Just happened again!

TypeError: Cannot read properties of null (reading 'slice')
    at a.externalFilters (RowFilterBuilder.vue?95b5:125:45)
    at Br (vue.runtime.esm.js:2987:30)
    at e.run (vue.runtime.esm.js:3503:21)
    at Xn (vue.runtime.esm.js:4090:17)
    at Array.<anonymous> (vue.runtime.esm.js:3113:20)
    at Vr (vue.runtime.esm.js:3035:16)

And after a minute or so:

Error: timeout exceeded when trying to connect
    at index.js:200:27

![image](https://github.com/beekeeper-studio/beekeeper-studio/assets/31410359/4d49ffec-2c45-44a4-93fd-7cd17ab4b5cd)

**Comment by tesioai** [comment]
same here, all connections failing, unchanged and all still working in dbeaver

Arch Linux, Postgres 16.2

connection test correctly displays "connection looks good"

**Comment by flystar233** [comment]
same issue on window10.

**Comment by tjnurmin** [comment]
Same here on Ubuntu 22. I had saved connections to servers with tens of databases with no default database.

When I edit a saved connection and add "default database", everything works. But I'd prefer not having to set the default db.

**Comment by rathboma** [comment]
@tjnurmin @flystar233 @tesioai @PlugNPush Can y'all download the builds from this page:
https://github.com/beekeeper-studio/beekeeper-studio/actions/runs/8513995786

And see if you still get the error?

Scroll down to the bottom (artifacts), for the OS downloads. These aren't signed or notarized, so you'll probably get install warnings.

Please let me know if this build fixes the problem. It should be merged soon if it does

**Comment by PlugNPush** [comment]
Will do tomorrow!

**Comment by tjnurmin** [comment]
I don't see any change - the problem is still there.

**Comment by rathboma** [comment]
@tjnurmin can you screen capture what you see happening?

**Comment by tjnurmin** [comment]
MySQL 8.0.36.

I'm using the AppImage build from the link above. The functionality is still the same: if a default database is not defined for the saved connection, I can't get to select any of them after the connection is made.

![Screenshot from 2024-04-02 16-36-18](https://github.com/beekeeper-studio/beekeeper-studio/assets/669108/e0873eb2-9b5c-4c3b-98b8-0644abdbfac5)

**Comment by tesioai** [comment]
mine seems to be working again on 4.2.5-1

after setting a default database it loaded, then after removing the default it appears to be working as normal

**Comment by tjnurmin** [comment]
> then after removing the default it appears to be working as normal

The same with me but it's still a regression as the default has to be set temporarily.

**Comment by rathboma** [comment]
That sounds even weirder. I can't replicate this behavior at all on the preview build, it seems to work no matter what I try.

@tesioai @tjnurmin If you have a connection that is still broken, would you record a video?

**Comment by mcanepa** [comment]
This started with v 4.2 (see #2039) and still happens in 4.2.5

I'm on debian 12 with mariadb 10.11.4

**Comment by rathboma** [comment]
@tjnurmin @mcanepa @PlugNPush I just released 4.2.7, please check if this problem is solved. I am still totally unable to replicate.

If not -- I'd ask that one of you make a screen recording of connecting to such a database to show us what is happening. There don't seem to be any errors I can find, and no-one on the BKS team can reproduce this problem, so your help would be invaluable.

**Comment by tjnurmin** [comment]
I would like to help but I had just 4 instances where

1. instance was created before migrating to 4.2
2. instance had tens of databases w/o a default one

As I had to access those servers this week, I set a default database for each of them. I can try but doubt I will be able to recreate the problem anymore.

**Comment by rathboma** [comment]
Any video recording would be much appreciated. I think it's a race condition of some sort, but I am unable to replicate

**Comment by rathboma** [comment]
Ok, a friend of mine could replicate, fix is coming up in 4.2.8, 3 super minor things caused this.
