### ISSUE TITLE
BUG: Flatpak SQLITE "Invalid SQL client" exception

### ISSUE THREAD

**Issue by knackstedt** [beekeeper-studio/beekeeper-studio#2237]
**Describe the bug**

**To Reproduce**
1. Launch a debian/ubuntu VM
2. Install beekepper via flathub
3. Open your filemanager
4. Double-click a sqlite database file
5. See error

**Expected behavior**
The sqlite database opens normally as it does under the normal installation

**Screenshots / Gifs**
![image](https://github.com/beekeeper-studio/beekeeper-studio/assets/29349167/d3120bb4-0986-4abf-8804-b636f3441d07)
![image](https://github.com/beekeeper-studio/beekeeper-studio/assets/29349167/657d1415-d847-4e6c-b0f5-2efc3888cfab)

If applicable, add screenshots or GIFS to help explain your problem.

**Version Information (please complete the following information):**
 - OS: Pop!_os 22.04, linuxfx11.2
 - App Version 4.3.4
 - Database type and version sqlite 3.37.2

**Additional context**
Appears to be an issue on the flatpak bundle itself. I was able to reproduce on a fresh VM simply by installing beekeeper via flatpak and attempting to open a sqlite database. Opening the database without the double-click action failed for presumably similar reasons.

Client developer tools output:
```
App.vue?89ba:69 Error: Invalid SQL client
    at qc (server.ts:24:11)
    at Object.for (connection-provider.ts:54:20)
    at y.connect (index.ts:375:43)
mounted @ App.vue?89ba:69
---
vue.runtime.esm.js:3019 Error: Invalid SQL client
    at qc (server.ts:24:11)
    at Object.for (connection-provider.ts:54:20)
    at y.connect (index.ts:375:43)
---
vue.runtime.esm.js:3019 TypeError: The "path" argument must be of type string. Received null
    at __node_internal_captureLargerStackTrace (node:internal/errors:464:5)
    at new NodeError (node:internal/errors:371:5)
    at validateString (node:internal/validators:119:11)
    at Object.basename (node:path:1309:5)
    at s.label (ConnectionListItem.vue:112:1)
    at e.get (vue.runtime.esm.js:3415:33)
    at e.evaluate (vue.runtime.esm.js:3516:27)
    at s.label (vue.runtime.esm.js:5492:25)
    at s.ng (ConnectionListItem.vue:1:702)
    at s.Sr.e._render (vue.runtime.esm.js:2654:28)
    at s.n (vue.runtime.esm.js:3844:27)
    at e.get (vue.runtime.esm.js:3415:33)
    at new e (vue.runtime.esm.js:3405:51)
    at Ln (vue.runtime.esm.js:3861:5)
    at s.to.$mount (vue.runtime.esm.js:8727:12)
    at init (vue.runtime.esm.js:4375:19)
    at m (vue.runtime.esm.js:6522:17)
    at f (vue.runtime.esm.js:6476:13)
    at S (vue.runtime.esm.js:6647:13)
    at R (vue.runtime.esm.js:6791:13)
    at k (vue.runtime.esm.js:6864:21)
    at R (vue.runtime.esm.js:6738:17)
    at k (vue.runtime.esm.js:6864:21)
    at R (vue.runtime.esm.js:6738:17)
    at k (vue.runtime.esm.js:6864:21)
    at R (vue.runtime.esm.js:6738:17)
    at k (vue.runtime.esm.js:6864:21)
    at R (vue.runtime.esm.js:6738:17)
    at k (vue.runtime.esm.js:6864:21)
    at R (vue.runtime.esm.js:6738:17)
    at k (vue.runtime.esm.js:6864:21)
    at s.__patch__ (vue.runtime.esm.js:7032:17)
    at s.e._update (vue.runtime.esm.js:3738:25)
    at s.n (vue.runtime.esm.js:3844:16)
    at e.get (vue.runtime.esm.js:3415:33)
    at e.run (vue.runtime.esm.js:3491:30)
    at Xn (vue.runtime.esm.js:4090:17)
    at Array.<anonymous> (vue.runtime.esm.js:3113:20)
    at Vr (vue.runtime.esm.js:3035:16)
```

**Comment by knackstedt** [comment]
On the client with the DEBUG flag (presumably) set, I can see this error when picking the database via the New Connection dialog. 
![image](https://github.com/beekeeper-studio/beekeeper-studio/assets/29349167/6c05c21c-8d5a-4c53-afaf-37a4ab7d0704)
```
{
    "code": "SQLITE_CANTOPEN",
    "message": "unable to open database file",
    "stack": "SqliteError: unable to open database file
    at new Database (/app/beekeeper-studio/resources/app.asar/node_modules/better-sqlite3/lib/database.js:63:26)
    at kl.rawExecuteQuery (app://./js/app.0ae9a66c.js:1:270950)
    at kl.driverExecuteSingle (app://./js/app.0ae9a66c.js:1:159636)
    at kl.connect (app://./js/app.0ae9a66c.js:1:263907)
    at async y.connect (app://./js/app.0ae9a66c.js:1:380923)"
}
```

**Comment by sammypanda** [comment]
I'm having this issue too with SQLite.

**Comment by not-night-but** [comment]
We don't actually manage the flatpak version of the app, and I believe it is also several versions behind. I'd recommend using the AppImage with AppImageLauncher for now. We are looking at bundling our own official flatpak version, but until then, we can't guarantee that everything works as it should on that version.
