### ISSUE TITLE
Errors During PostgreSQL Database Dump on Windows Server 2016

### ISSUE THREAD

**Issue by rathboma** [beekeeper-studio/beekeeper-studio#2475]
### Description

Encountered multiple errors while attempting to run a database dump for PostgreSQL version 10.10.1 on Windows Server 2016 Standard. Errors primarily involve `TypeError: Cannot set properties of null` and `TypeError: Cannot read properties of null`. Errors also indicate issues with log file operations and file paths.

### Environment

- **OS:** Windows Server 2016 Standard
- **Version:** 1607
- **OS Build:** 14393.6796
- **PostgreSQL Version:** 10.10.1

### Errors

```
TypeError: Cannot set properties of null (setting 'config')
  at y.updateConfig (app.53d0a705.js:1:444296)
  at chunk-vendors.b7016fdb.js:2920:6436
  at chunk-vendors.b7016fdb.js:2920:7470
  at Array.forEach (<anonymous>)
  at chunk-vendors.b7016fdb.js:2920:7449
  at y._withCommit (chunk-vendors.b7016fdb.js:2920:9291)
  at y.commit (chunk-vendors.b7016fdb.js:2920:7423)
  at y.commit (chunk-vendors.b7016fdb.js:2920:4074)
  at Object.S.i.commit (chunk-vendors.b7016fdb.js:2920:5882)
  at y.reset (app.53d0a705.js:1:444648)
  at Array.<anonymous> (chunk-vendors.b7016fdb.js:2920:6545)
  at y.dispatch (chunk-vendors.b7016fdb.js:2920:7880)
  at y.dispatch (chunk-vendors.b7016fdb.js:2920:4024)
  at s.mounted (app.53d0a705.js:1:727945)
  at Br (chunk-vendors.b7016fdb.js:2884:24373)
  at jn (chunk-vendors.b7016fdb.js:2884:33324)
Fr @ chunk-vendors.b7016fdb.js:2884

chunk-vendors.b7016fdb.js:2884 TypeError: Cannot read properties of null (reading 'deleteFile')
  at hh.deleteLogFile (app.53d0a705.js:1:421010)
  at y.deleteLogFile (app.53d0a705.js:1:446592)
  at Array.<anonymous> (chunk-vendors.b7016fdb.js:2920:6545)
  at y.dispatch (chunk-vendors.b7016fdb.js:2920:7880)
  at y.dispatch (chunk-vendors.b7016fdb.js:2920:4024)
  at s.beforeDestroy (app.53d0a705.js:1:728137)
  at Br (chunk-vendors.b7016fdb.js:2884:24373)
  at jn (chunk-vendors.b7016fdb.js:2884:33324)
  at s.e.$destroy (chunk-vendors.b7016fdb.js:2884:31256)
  at destroy (chunk-vendors.b7016fdb.js:2884:36915)
  at C (chunk-vendors.b7016fdb.js:2884:55119)
  at C (chunk-vendors.b7016fdb.js:2884:55218)
  at A (chunk-vendors.b7016fdb.js:2884:55301)
  at R (chunk-vendors.b7016fdb.js:2884:56209)
  at k (chunk-vendors.b7016fdb.js:2884:56811)
  at R (chunk-vendors.b7016fdb.js:2884:55731)
Fr @ chunk-vendors.b7016fdb.js:2884

node:fs:585 Uncaught (in promise) Error: ENOENT: no such file or directory, open 'undefined\temp\tmp-16565nnhe0ch1Z87.txt'
  at Object.openSync (node:fs:585:3)
  at Object.func [as openSync] (node:electron/js2c/asar_bundle:5:1812)
  at Object.O [as fileSync] (chunk-vendors.b7016fdb.js:67:1981)
  at new lh (app.53d0a705.js:1:415594)
  at hh.initLogFile (app.53d0a705.js:1:420841)
  at y.execute (app.53d0a705.js:1:445360)
  at Array.<anonymous> (chunk-vendors.b7016fdb.js:2920:6545)
  at y.dispatch (chunk-vendors.b7016fdb.js:2920:7880)
  at y.dispatch (chunk-vendors.b7016fdb.js:2920:4024)
  at s.runBackup (app.53d0a705.js:1:727405)
  at Br (chunk-vendors.b7016fdb.js:2884:24360)
  at s.r (chunk-vendors.b7016fdb.js:2884:14169)
  at Br (chunk-vendors.b7016fdb.js:2884:24360)
  at s.Rn.e.$emit (chunk-vendors.b7016fdb.js:2884:30373)
  at s.nextStep (app.53d0a705.js:1:647575)

app.53d0a705.js:1 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'write')
  at hh.writeToLog (app.53d0a705.js:1:420971)
  at y.addLogMessage (app.53d0a705.js:1:444382)
  at chunk-vendors.b7016fdb.js:2920:6436
  at chunk-vendors.b7016fdb.js:2920:7470
  at Array.forEach (<anonymous>)
  at chunk-vendors.b7016fdb.js:2920:7449
  at y._withCommit (chunk-vendors.b7016fdb.js:2920:9291)
  at y.commit (chunk-vendors.b7016fdb.js:2920:7423)
  at y.commit (chunk-vendors.b7016fdb.js:2920:4074)
  at Object.S.i.commit (chunk-vendors.b7016fdb.js:2920:5882)
  at hh.e.getters.commandClient.addLogCallback [as _addLogCallback] (app.53d0a705.js:1:445419)
  at app.53d0a705.js:1:422939
  at Array.forEach (<anonymous>)
  at Socket.<anonymous> (app.53d0a705.js:1:422897)
  at Socket.emit (node:events:390:28)
  at addChunk (node:internal/streams/readable:315:12)

chunk-vendors.b7016fdb.js:2884 TypeError: Cannot read properties of null (reading 'path')
  at hh.get logPath [as logPath] (app.53d0a705.js:1:421058)
  at logFilePath (app.53d0a705.js:1:443735)
  at R.e._wrappedGetters.<computed>.e._wrappedGetters.<computed> (chunk-vendors.b7016fdb.js:2920:6872)
  at to.<anonymous> (chunk-vendors.b7016fdb.js:2920:1404)
  at e.get (chunk-vendors.b7016fdb.js:2884:27901)
  at e.evaluate (chunk-vendors.b7016fdb.js:2884:28901)
  at to.backups/logFilePath (chunk-vendors.b7016fdb.js:2884:42380)
  at Object.get [as backups/logFilePath] (chunk-vendors.b7016fdb.js:2920:4862)
  at s.j.forEach.r.<computed> (chunk-vendors.b7016fdb.js:2920:10184)
  at e.get (chunk-vendors.b7016fdb.js:2884:27901)
  at e.evaluate (chunk-vendors.b7016fdb.js:2884:28901)
  at s.logFile (chunk-vendors.b7016fdb.js:2884:42380)
  at s.openLog (app.53d0a705.js:1:727779)
  at Br (chunk-vendors.b7016fdb.js:2884:24360)
  at s.r (chunk-vendors.b7016fdb.js:2884:14169)
  at Br (chunk-vendors.b7016fdb.js:2884:24360)

chunk-vendors.b7016fdb.js:2884 TypeError: Cannot read properties of null (reading 'path')
  at hh.get logPath [as logPath] (app.53d0a705.js:1:421058)
  at logFilePath (app.53d0a705.js:1:443735)
  at R.e._wrappedGetters.<computed>.e._wrappedGetters.<computed> (chunk-vendors.b7016fdb.js:2920:6872)
  at to.<anonymous> (chunk-vendors.b7016fdb.js:2920:1404)
  at e.get (chunk-vendors.b7016fdb.js:2884:27901)
  at e.evaluate (chunk-vendors.b7016fdb.js:2884:28901)
  at to.backups/logFilePath (chunk-vendors.b7016fdb.js:2884:42380)
  at Object.get [as backups/logFilePath] (chunk-vendors.b7016fdb.js:2920:4862)
  at s.j.forEach.r.<computed> (chunk-vendors.b7016fdb.js:2920:10184)
  at e.get (chunk-vendors.b7016fdb.js:2884:27901)
  at e.evaluate (chunk-vendors.b7016fdb.js:2884:28901)
  at s.logFile (chunk-vendors.b7016fdb.js:2884:42380)
  at showLog (app.53d0a705.js:1:727840)
  at Br (chunk-vendors.b7016fdb.js:2884:24360)
  at s.r (chunk-vendors.b7016fdb.js:2884:14169)
  at Br (chunk-vendors.b7016fdb.js:2884:24360)
Fr @ chunk-vendors.b7016fdb.js:2884
```

### Steps to Reproduce

1. Run a database backup for PostgreSQL v10.10.1 on Windows Server 2016 Standard.
2. Observe the console (dev tools) for the mentioned errors.

### Additional Information

- Updates are being installed on the server to check if the issue persists with the latest version/build.
- If further information is needed, please let me know.
***

*This issue was extracted from an email thread by [IssueWizard](https://issuewizard.com)*

**Comment by not-night-but** [comment]
I believe I ran into this when refactoring for the utility process and fixed it. Needs to be checked again though.
