### ISSUE TITLE
No window on MacOS v 1.6.x

### ISSUE THREAD

**Issue by oojacoboo** [beekeeper-studio/beekeeper-studio#249]
This is a fun one.  Downloaded it (1.6.4) for Mac OS (10.15.5), unpacked the dmg, moved the app to the `~/Applications` dir, and opened it.  I have the icon in the dock, I have the menu bar, but I don't have any windows.  Additionally, neither the `Window`, nor the `View` from the menu-bar have a main window option.  And there isn't anything else that seems likely to initiate the app.

**Comment by rathboma** [comment]
Damn, we've seen this too, and I've been unable to replicate reliably. It only seems to affect MacOS.

The 1.5.x releases should work.

Before you move back, can you do me a favor and run it with this command in the terminal then copy and paste the output for me?:
```
~/Applications/Beekeeper\ Studio.app/Contents/MacOS/Beekeeper\ Studio
```

**Comment by oojacoboo** [comment]
Sorry, `/Applications` at the volume root, not user home dir.  Here is the output.  It looks like I don't have SQLite installed with Node.  I don't really want it either.  I haven't done any Mac OS development, but is it common to use SQLite for app storage?  What's SQLite used for here?  And, I'd assume, if this app is installing SQLite, that it's somehow sandboxed and not installed globally?

```
(node:51185) UnhandledPromiseRejectionWarning: DriverPackageNotInstalledError: SQLite package has not been found installed. Try to install it: npm install sqlite3 --save
    at new DriverPackageNotInstalledError (/Applications/Beekeeper Studio.app/Contents/Resources/app.asar/node_modules/typeorm/error/DriverPackageNotInstalledError.js:10:28)
    at SqliteDriver.loadDependencies (/Applications/Beekeeper Studio.app/Contents/Resources/app.asar/node_modules/typeorm/driver/sqlite/SqliteDriver.js:120:19)
    at new SqliteDriver (/Applications/Beekeeper Studio.app/Contents/Resources/app.asar/node_modules/typeorm/driver/sqlite/SqliteDriver.js:26:15)
    at DriverFactory.create (/Applications/Beekeeper Studio.app/Contents/Resources/app.asar/node_modules/typeorm/driver/DriverFactory.js:42:24)
    at new Connection (/Applications/Beekeeper Studio.app/Contents/Resources/app.asar/node_modules/typeorm/connection/Connection.js:54:59)
    at ConnectionManager.create (/Applications/Beekeeper Studio.app/Contents/Resources/app.asar/node_modules/typeorm/connection/ConnectionManager.js:56:26)
    at /Applications/Beekeeper Studio.app/Contents/Resources/app.asar/node_modules/typeorm/index.js:207:66
    at step (/Applications/Beekeeper Studio.app/Contents/Resources/app.asar/node_modules/tslib/tslib.js:141:27)
    at Object.next (/Applications/Beekeeper Studio.app/Contents/Resources/app.asar/node_modules/tslib/tslib.js:122:57)
    at /Applications/Beekeeper Studio.app/Contents/Resources/app.asar/node_modules/tslib/tslib.js:115:75
(node:51185) UnhandledPromiseRejectionWarning: DriverPackageNotInstalledError: SQLite package has not been found installed. Try to install it: npm install sqlite3 --save
    at new DriverPackageNotInstalledError (/Applications/Beekeeper Studio.app/Contents/Resources/app.asar/node_modules/typeorm/error/DriverPackageNotInstalledError.js:10:28)
    at SqliteDriver.loadDependencies (/Applications/Beekeeper Studio.app/Contents/Resources/app.asar/node_modules/typeorm/driver/sqlite/SqliteDriver.js:120:19)
    at new SqliteDriver (/Applications/Beekeeper Studio.app/Contents/Resources/app.asar/node_modules/typeorm/driver/sqlite/SqliteDriver.js:26:15)
    at DriverFactory.create (/Applications/Beekeeper Studio.app/Contents/Resources/app.asar/node_modules/typeorm/driver/DriverFactory.js:42:24)
    at new Connection (/Applications/Beekeeper Studio.app/Contents/Resources/app.asar/node_modules/typeorm/connection/Connection.js:54:59)
    at ConnectionManager.create (/Applications/Beekeeper Studio.app/Contents/Resources/app.asar/node_modules/typeorm/connection/ConnectionManager.js:56:26)
    at /Applications/Beekeeper Studio.app/Contents/Resources/app.asar/node_modules/typeorm/index.js:207:66
    at step (/Applications/Beekeeper Studio.app/Contents/Resources/app.asar/node_modules/tslib/tslib.js:141:27)
    at Object.next (/Applications/Beekeeper Studio.app/Contents/Resources/app.asar/node_modules/tslib/tslib.js:122:57)
    at /Applications/Beekeeper Studio.app/Contents/Resources/app.asar/node_modules/tslib/tslib.js:115:75
(node:51185) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:51185) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:51185) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:51185) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by rathboma** [comment]
I've been doing some investigation -- I think this may be a misleading error. I get this error, but my app launching works.

My co-creator has been able to replicate the error, so we're investigating now

**Comment by rathboma** [comment]
can you open console.app, search at the top right for 'beekeeper', then open the app and see if you see any errors?

**Comment by oojacoboo** [comment]
Wow, console.app has been updated quite a bit since I last saw it.  Here is what I found:

```
default	18:59:13.303935-0400	Beekeeper Studio	FRONTLOGGING: version 1
default	18:59:13.303960-0400	Beekeeper Studio	Registering, pid=53879
default	18:59:13.305273-0400	Beekeeper Studio	CHECKIN: pid=53879
default	18:59:13.410301-0400	Beekeeper Studio	CHECKEDIN: pid=53879 asn=0x0-0x291291 foreground=1
default	18:59:13.430183-0400	Beekeeper Studio	Registered, pid=53879 ASN=0x0,0x291291
default	18:59:13.430383-0400	Beekeeper Studio	Registered, pid=53879 cgConnectionID=142c2f
default	18:59:13.434292-0400	Beekeeper Studio	BringForward: pid=53879 asn=0x0-0x291291 bringForward=1 foreground=1 uiElement=0 launchedByLS=1 modifiersCount=1 allDisabled=0
default	18:59:13.434814-0400	Beekeeper Studio	BringFrontModifier: pid=53879 asn=0x0-0x291291 Modifier 0 hideAfter=0 hideOthers=0 dontMakeFrontmost=0 mouseDown=0/0 seed=0/0
default	18:59:13.435125-0400	Beekeeper Studio	BringForward: pid=53879 asn=0x0-0x291291
default	18:59:13.435302-0400	Beekeeper Studio	SetFrontProcess: asn=0x0-0x291291 options=0
default	18:59:13.447957-0400	Beekeeper Studio	Current system appearance, (HLTB: 1), (SLS: 0)
default	18:59:13.452728-0400	Beekeeper Studio	Post-registration system appearance: (HLTB: 1)
default	18:59:13.719650-0400	Beekeeper Studio	NSApp cache appearance:
-NSRequiresAquaSystemAppearance: 0
-appearance: (null)
-effectiveAppearance: <NSCompositeAppearance: 0x600002251d00
 (
    "<NSAquaAppearance: 0x600002251c00>",
    "<NSSystemAppearance: 0x600002250d00>"
)>
default	18:59:14.166948-0400	Beekeeper Studio	Registering for test daemon availability notify post.
default	18:59:14.167401-0400	Beekeeper Studio	notify_get_state check indicated test daemon not ready.
default	18:59:14.235110-0400	Beekeeper Studio	SignalReady: pid=53879 asn=0x0-0x291291
default	18:59:14.236933-0400	Beekeeper Studio	SIGNAL: pid=53879 asn=0x0x-0x2691729
default	18:59:14.481817-0400	Beekeeper Studio Helper (GPU)	MessageTracer: Falling back to default whitelist
default	18:59:14.481862-0400	Beekeeper Studio Helper (GPU)	XPC connection invalidated (daemon unloaded or disabled)
default	18:59:14.487554-0400	Beekeeper Studio Helper (GPU)	Can't open default search tree file: Operation not permitted
default	18:59:14.533899-0400	Beekeeper Studio Helper (GPU)	GVA info: preferred scaler idx 1
default	18:59:14.548070-0400	Beekeeper Studio Helper (GPU)	MessageTracer: Falling back to default whitelist
default	18:59:14.548109-0400	Beekeeper Studio Helper (GPU)	Can't open default search tree file: Operation not permitted
default	18:59:15.146574-0400	Beekeeper Studio	nw_path_evaluator_start [FDE7A2AB-9FEC-40DE-A322-BA2283EE4649 <NULL> generic, indefinite]
	path: satisfied (Path is satisfied), interface: en0, ipv4, dns
default	18:59:15.805021-0400	Beekeeper Studio Helper	nw_path_evaluator_start [BF5D395B-E987-453B-87AC-50DFCDCD31CD <NULL> generic, indefinite]
	path: satisfied (Path is satisfied), interface: en0, ipv4, dns
default	18:59:24.227577-0400	Beekeeper Studio	LSExceptions shared instance invalidated for timeout.
default	18:59:24.286777-0400	Beekeeper Studio Helper (GPU)	LSExceptions shared instance invalidated for timeout.
fault	19:00:44.489276-0400	Beekeeper Studio Helper (GPU)	Failed to get Metal shader cache main folder: failed to lookup DARWIN_USER_CACHE_DIR err:5
```

**Comment by rathboma** [comment]
@oojacoboo can you try version 1.6.9? https://github.com/beekeeper-studio/beekeeper-studio/releases/tag/v1.6.9

**Comment by rathboma** [comment]
Got some confirmations that this is fixed. Thank god.

**Comment by oojacoboo** [comment]
@rathboma no dice.

![image](https://user-images.githubusercontent.com/764664/88120663-71503600-cb91-11ea-84c7-146627c51845.png)

**Comment by rathboma** [comment]
Ah, that's because you have to go to settings - security - general and allow running apps from other sources I think.

**Comment by oojacoboo** [comment]
I don't think that's it.  I mean, I've had that enabled for years.  I know you had to re-enable again more recently, but that's been done as well.

![image](https://user-images.githubusercontent.com/764664/88129104-3a841b00-cba5-11ea-93a3-4ff070e699ac.png)

That said, it does say "identified developers".  Is it "signed"?

**Comment by rathboma** [comment]
Yes it is signed, ant notarized.

That's weird. I double checked my settings and I don't get that error:

<img width="484" alt="Screen Shot 2020-07-21 at 10 11 10 PM" src="https://user-images.githubusercontent.com/279769/88130054-3bb24980-cb9f-11ea-8709-fd2d3a20fe14.png">

Questions:
- Are you using the DMG or Zip? I think maybe only the DMG is signed?
- Can you run from the terminal again and post any output?

**Comment by oojacoboo** [comment]
Bingo!  I downloaded the zip b/c it said "mac".  Just tried the `.dmg` and it's working now.  So, issue resolved.  But you might want to nix that zip and add `mac` to the dmg so people are aware.  Thanks for the help.

**Comment by rathboma** [comment]
Oh man, good find! Thanks for the amazing help debugging.
