### ISSUE TITLE
BUG: Built app fails to load with a missing column error

### ISSUE THREAD

**Issue by rathboma** [beekeeper-studio/beekeeper-studio#2495]
```
[2024-10-11 19:22:03.491] [info]                      initializing background
[2024-10-11 19:22:06.149] [error] (UTILITY)           19:22:06.146 (UtilityProcess)      > SqliteError: no such column: LicenseKey.maxAllowedAppRelease
    at Database.prepare (C:\Users\mazmi\AppData\Local\Programs\beekeeper-studio\resources\app.asar\node_modules\better-sqlite3\lib\methods\wrappers.js:5:21)
    at BetterSqlite3QueryRunner.getStmt (C:\Users\mazmi\AppData\Local\Programs\beekeeper-studio\resources\app.asar\dist\utility.js:168377:39)
    at async BetterSqlite3QueryRunner.query (C:\Users\mazmi\AppData\Local\Programs\beekeeper-studio\resources\app.asar\dist\utility.js:168411:22)
    at async _SelectQueryBuilder.loadRawResults (C:\Users\mazmi\AppData\Local\Programs\beekeeper-studio\resources\app.asar\dist\utility.js:136019:25)
    at async _SelectQueryBuilder.executeEntitiesAndRawResults (C:\Users\mazmi\AppData\Local\Programs\beekeeper-studio\resources\app.asar\dist\utility.js:135911:24)
    at async _SelectQueryBuilder.getRawAndEntities (C:\Users\mazmi\AppData\Local\Programs\beekeeper-studio\resources\app.asar\dist\utility.js:135017:27)
    at async _SelectQueryBuilder.getMany (C:\Users\mazmi\AppData\Local\Programs\beekeeper-studio\resources\app.asar\dist\utility.js:135074:25)

[2024-10-11 19:22:06.146] [error] (UtilityProcess)      SqliteError: no such column: LicenseKey.maxAllowedAppRelease
    at Database.prepare (C:\Users\mazmi\AppData\Local\Programs\beekeeper-studio\resources\app.asar\node_modules\better-sqlite3\lib\methods\wrappers.js:5:21)
    at BetterSqlite3QueryRunner.getStmt (C:\Users\mazmi\AppData\Local\Programs\beekeeper-studio\resources\app.asar\dist\utility.js:168377:39)
    at async BetterSqlite3QueryRunner.query (C:\Users\mazmi\AppData\Local\Programs\beekeeper-studio\resources\app.asar\dist\utility.js:168411:22)
    at async _SelectQueryBuilder.loadRawResults (C:\Users\mazmi\AppData\Local\Programs\beekeeper-studio\resources\app.asar\dist\utility.js:136019:25)
    at async _SelectQueryBuilder.executeEntitiesAndRawResults (C:\Users\mazmi\AppData\Local\Programs\beekeeper-studio\resources\app.asar\dist\utility.js:135911:24)
    at async _SelectQueryBuilder.getRawAndEntities (C:\Users\mazmi\AppData\Local\Programs\beekeeper-studio\resources\app.asar\dist\utility.js:135017:27)
    at async _SelectQueryBuilder.getMany (C:\Users\mazmi\AppData\Local\Programs\beekeeper-studio\resources\app.asar\dist\utility.js:135074:25)
```

![image](https://github.com/user-attachments/assets/996b5243-59c2-4005-a11b-d60e1dd349d8)

**Comment by azmy60** [comment]
This is weird. I built the latest master with your fix on windows using msys2 and I'm still getting the same errors. The errors seem to block the app from initiating the window. I'm taking a look.

**Comment by azmy60** [comment]
So I just found the cause! The `main.ts` runs the migration on `app.db`, but the `utility.ts` reads the `app-dev.db`. For some reason the `platformInfo.isDevelopment` flag is inconsistent within both files.
