### ISSUE TITLE
Update to 5.0.0.alpha: Error: DataSource is not set for this entity.

### ISSUE THREAD

**Issue by jancoow** [beekeeper-studio/beekeeper-studio#2616]
**Describe the bug**
I want to test the alpha version, however I'm unable to launch it.

```
12:07:17.956 (UTILITY)                    › 12:07:17.955 (UtilityProcess)      › HANDLER: ERROR Error: DataSource is not set for this entity.
    at UserSetting.getRepository (/usr/lib/beekeeper-studio/app.asar/dist/utility.js:188982:17)
    at UserSetting.find (/usr/lib/beekeeper-studio/app.asar/dist/utility.js:189143:21)
    at appdb/setting/find (/usr/lib/beekeeper-studio/app.asar/dist/utility.js:378708:25)
    at runHandler (/usr/lib/beekeeper-studio/app.asar/dist/utility.js:430922:27)
    at MessagePortMain.<anonymous> (/usr/lib/beekeeper-studio/app.asar/dist/utility.js:430951:5)
    at MessagePortMain.emit (node:events:519:28)
    at MessagePortMain._internalPort.emit (node:electron/js2c/utility_init:2:2619)
12:07:17.955 (UtilityProcess)      › HANDLER: ERROR Error: DataSource is not set for this entity.
    at UserSetting.getRepository (/usr/lib/beekeeper-studio/app.asar/dist/utility.js:188982:17)
    at UserSetting.find (/usr/lib/beekeeper-studio/app.asar/dist/utility.js:189143:21)
    at appdb/setting/find (/usr/lib/beekeeper-studio/app.asar/dist/utility.js:378708:25)
    at runHandler (/usr/lib/beekeeper-studio/app.asar/dist/utility.js:430922:27)
    at MessagePortMain.<anonymous> (/usr/lib/beekeeper-studio/app.asar/dist/utility.js:430951:5)
    at MessagePortMain.emit (node:events:519:28)
    at MessagePortMain._internalPort.emit (node:electron/js2c/utility_init:2:2619)

12:07:17.955 (renderer/utilityconnection) › GOT ERROR BACK FOR REQUEST ID:  bd2be398-576c-4958-8b60-551269a6bc40
12:07:17.955 (renderer/utilityconnection) › GOT ERROR BACK FOR REQUEST ID:  fe3054fd-6bc0-49f4-8732-116a145cd6fc
12:07:17.955 (renderer/utilityconnection) › GOT ERROR BACK FOR REQUEST ID:  c44024bc-3a52-4490-871f-b0fafe4e5795
12:07:17.957 (UTILITY)                    › 12:07:17.956 (UtilityProcess)      › RECEIVED REQUEST FOR NAME, ID:  appdb/setting/find 9c94b6e9-8c07-4173-b903-6f65a69d3791

12:07:17.957 (UTILITY)                    › 12:07:17.956 (UtilityProcess)      › HANDLER: ERROR Error: DataSource is not set for this entity.
    at UserSetting.getRepository (/usr/lib/beekeeper-studio/app.asar/dist/utility.js:188982:17)
    at UserSetting.find (/usr/lib/beekeeper-studio/app.asar/dist/utility.js:189143:21)
    at appdb/setting/find (/usr/lib/beekeeper-studio/app.asar/dist/utility.js:378708:25)
    at runHandler (/usr/lib/beekeeper-studio/app.asar/dist/utility.js:430922:27)
    at MessagePortMain.<anonymous> (/usr/lib/beekeeper-studio/app.asar/dist/utility.js:430951:5)
    at MessagePortMain.emit (node:events:519:28)
    at MessagePortMain._internalPort.emit (node:electron/js2c/utility_init:2:2619)

12:07:17.956 (renderer/utilityconnection) › GOT ERROR BACK FOR REQUEST ID:  5509ea11-be24-4216-85d4-a13eeac392f5
12:07:17.956 (renderer/utilityconnection) › GOT ERROR BACK FOR REQUEST ID:  9c94b6e9-8c07-4173-b903-6f65a69d3791
```

**To Reproduce**
1. Update from 4.6.8-1 to 5.0.0.alpha
2. Start the application

**Version Information (please complete the following information):**
 - OS: Arch Linux
 - App Version  5.0.0.alpha 
 - https://aur.archlinux.org/packages/beekeeper-studio-git

**Comment by not-night-but** [comment]
I think this might just be an issue with the packaging. We don't manage the AUR version of the app, and I can only replicate this issue when using that version of the app. @jancoow I'd recommend using the AppImage version of the app with `AppImageLauncher`: https://github.com/beekeeper-studio/beekeeper-studio/releases/tag/v5.0.0-beta.5

**Comment by rathboma** [comment]
@jancoow Once 5.0 is out and we've moved to a single binary I'm going to start being more involved in these third party distribution channels. Stay tuned! For now, please use a supported package.
