### ISSUE TITLE
BUG: Version 5.0.8 Appimage never gets past Loading screen

### ISSUE THREAD

**Issue by mikeybob** [beekeeper-studio/beekeeper-studio#2650]
**Describe the bug**
Version 5.0.8 Appimage never gets past Loading screen

**To Reproduce**
Download appimage
use appimage launcher or gear loader
app starts
displays Loading and animation.
Never progresses past that.

start and let me do my thing.

**Screenshots / Gifs**
If applicable, add screenshots or GIFS to help explain your problem.

**Version Information (please complete the following information):**
 - OS:Fedora 41 KDE
 - App Version 5.0.8
 - Database type and version: Never gets that far.

**Additional context**
Anything else you think might be helpful

**Comment by not-night-but** [comment]
@mikeybob Hey! Would you be able to provide any errors in the logs? (`~/.config/beekeeper-studio/logs/`)

**Comment by mikeybob** [comment]
Sure, no problem. main.log 

2024-12-13 19:30:20.975] [info]  (UtilityProcess)      RECEIVED REQUEST FOR NAME, ID:  enum/load 7d69f192-e4c0-4921-a156-9f11583afc1b
[2024-12-13 19:30:20.976] [info]  (UTILITY)                    19:30:20.975 (UtilityProcess)      › RECEIVED REQUEST FOR NAME, ID:  enum/load 7d69f192-e4c0-4921-a156-9f11583afc1b

[2024-12-13 19:30:20.977] [error] (UtilityProcess)      HANDLER: ERROR Error: ENUM LOADING ERROR:  SyntaxError: Unexpected token ']', ..."
    },
  ]
" is not valid JSON
    at enum/load (/tmp/.mount_BeekeeJ9v338/resources/app.asar/dist/utility.js:430356:13)
[2024-12-13 19:30:20.977] [error] (UTILITY)                    19:30:20.977 (UtilityProcess)      › HANDLER: ERROR Error: ENUM LOADING ERROR:  SyntaxError: Unexpected token ']', ..."
    },
  ]
" is not valid JSON
    at enum/load (/tmp/.mount_BeekeeJ9v338/resources/app.asar/dist/utility.js:430356:13)

[2024-12-13 19:30:20.978] [error] (renderer/utilityconnection) GOT ERROR BACK FOR REQUEST ID:  7d69f192-e4c0-4921-a156-9f11583afc1b
[2024-12-13 19:31:20.974] [info]  (UtilityProcess)      RECEIVED REQUEST FOR NAME, ID:  license/getStatus 1f7e99d7-b660-4f53-8552-d2ee699fbc6a
[2024-12-13 19:31:20.975] [info]  (UTILITY)                    19:31:20.974 (UtilityProcess)      › RECEIVED REQUEST FOR NAME, ID:  license/getStatus 1f7e99d7-b660-4f53-8552-d2ee699fbc6a

[2024-12-13 19:31:20.980] [info]  (UtilityProcess)      RECEIVED REQUEST FOR NAME, ID:  license/get c19af897-efda-4bdd-9386-d5567cb2863b
[2024-12-13 19:31:20.981] [info]  (UTILITY)                    19:31:20.980 (UtilityProcess)      › RECEIVED REQUEST FOR NAME, ID:  license/get c19af897-efda-4bdd-9386-d5567cb2863b

[2024-12-13 19:32:20.974] [info]  (UtilityProcess)      RECEIVED REQUEST FOR NAME, ID:  license/getStatus 5281afbb-9185-447b-8ac9-d510f723a132
[2024-12-13 19:32:20.976] [info]  (UTILITY)                    19:32:20.974 (UtilityProcess)      › RECEIVED REQUEST FOR NAME, ID:  license/getStatus 5281afbb-9185-447b-8ac9-d510f723a132

[2024-12-13 19:32:21.009] [info]  (UtilityProcess)      RECEIVED REQUEST FOR NAME, ID:  license/get b9c82396-abfe-4350-8049-1b81ef077acf
[2024-12-13 19:32:21.010] [info]  (UTILITY)                    19:32:21.009 (UtilityProcess)      › RECEIVED REQUEST FOR NAME, ID:  license/get b9c82396-abfe-4350-8049-1b81ef077acf

[2024-12-13 19:33:05.301] [info]  (UtilityProcess)      REMOVING STATE FOR:  246523e6-1a46-4f71-8c40-2997b1af7c58
[2024-12-13 19:33:05.302] [info]  (UTILITY)                    19:33:05.301 (UtilityProcess)      › REMOVING STATE FOR:  246523e6-1a46-4f71-8c40-2997b1af7c58

**Comment by mikeybob** [comment]
Sweet. Works perfectly.  I was playing around with enums during the beta. I never thought about checking it. Thanks for the fix 👍🏼
