### ISSUE TITLE
FEAT: Auto recconect

### ISSUE THREAD

**Issue by zhuharev** [beekeeper-studio/beekeeper-studio#389]
**Is your feature request related to a problem? Please describe.**
When I leave studio opened long time, and after try `select 1;`, query slate forever. 

**Describe the solution you'd like**
I think we need check connection health and reconnect if needed before sending query.

**Context**
I use SSH connection. Need check both connections to database and to remote server&

**Comment by rathboma** [comment]
Ah, I think this is probably the SSH tunnel timing out.

Questions: 
- Does your computer suspend in between connecting and going back?
- What OS are you using?

Can you check the log file to see if there are any errors?

Linux: ~/.config/beekeeper-studio/logs/{process type}.log
MacOS: ~/Library/Logs/beekeeper-studio/{process type}.log
Windows: %USERPROFILE%\AppData\Roaming\beekeeper-studio\logs\{process type}.log

**Comment by evs-xsarus** [comment]
I'm using Ubuntu Unity 20.04 - https://ubuntuunity.org/ without suspending.

To prevent disconnects in a terminal SSH session, I've set these:

*/home/evs/.ssh/config*
```
# This helps prevent disconnects. Equivalent to the ClientAlive* settings on the serve
ServerAliveInterval 60
ServerAliveCountMax 120
# This is counter-intuitive. TCPKeepAlive should be set to no to help eliminate disconnects.
TCPKeepAlive no
```

I've performed a tail on all logs while leaving Beekeeper running in the background for about 7 minutes. Nothing appeared about a SSH-tunnel being dropped. Coming back to Beekeeper and running the same query:

```sql
SHOW FULL PROCESSLIST
```
now only shows 'Query Running...'. Still, the logs remains empty.

I've cancelled the query after 10 minutes, the logs stay empty. Opening the data view for a table now shows an error:

> No primary key detected, table editing is disabled.

**Comment by MatteoAvalle** [comment]
I can confirm I see the same issue when using SSH tunneling.
The related error line in the renderer.log file is:
`[2021-05-28 13:29:17.223] [error] (mysql)        Connection fatal error "Error: Connection lost: The server closed the connection.\n    at Socket.<anonymous> (C:\\Users\\me\\AppData\\Local\\Programs\\beekeeper-studio\\resources\\app.asar\\node_modules\\mysql2\\lib\\connection.js:91:31)\n    at Socket.emit (events.js:223:5)\n    at TCP.<anonymous> (net.js:664:12)"`

**Comment by countless-integers** [comment]
This would be great. Even a button somewhere to "Refresh" the connection (similar to table view) would help a lot.

**Comment by mcmahanp** [comment]
This is a pretty big issue for me. I have a remote DB that I connect to over ssh. I love this app (it is nearly everything I've ever wanted in a DB frontend), but this issue alone cuts severely into its usefulness. Currently, whenever I encounter this issue (e.g. if I close my laptop, or just leave the app idle for a while) I have to disconnect and reconnect, which closes the window and any unsaved queries or results I have open in tabs. This is a big workflow issue.

I'd be very happy even with a simple "reconnect" button or menu item -- perhaps right next to 'disconnect' in the file menu on Mac OS -- that doesn't require the window to close and open.

**Comment by warna720** [comment]
Can also confirm having this issue. At this point any solution to not loose all my tabs would be nice.

**Comment by AnTheMaker** [comment]
This happens for me too.
After about 1 minute of not running any queries, the connection breaks and I have to disconnect and reconnect again (I'm using an SSH tunnel in beekeeper studio).
For me, this only happens in some networks - not all. It seems to be an inactivity timeout with the SSH connection.

To fix this outside of beekeper studio for my normal SSH connections, I configured ssh to send a "heartbeat" every 60 seconds (`ServerAliveInterval 60`). This fixes the timeout for my normal ssh sessions.
Would it be possible to add a similar setting to beekeper studio? This is a really annoying bug and a highly needed feature (at least for people like us who have this issue in some networks).

Thanks a lot @rathboma & keep up the great work with beekeeper studio!

**Comment by anilpuliyeril** [comment]
@rathboma do you have a timeline or a workaround for the issue?

**Comment by rathboma** [comment]
My goal is to wrap up the next release then circle back and focus on tweaks and fixes (like this one) for a couple of weeks. So hopefully it'll get fixed soon!

**Comment by ckdake** [comment]
@rathboma I'm investigating a reconnect issue, from how Beekeper seems to work today, this feature is in and working as expected, right?

**Comment by rathboma** [comment]
Right now:

- SSH Keepalive keeps SSH connections alive, but sometimes connections can drop
- Beekeeper should figure this out and reconnect
- We should tell the user we are reconnecting

Also: Provide a 'reconnect' button in the connection menu in the bottom left.

**Comment by inspire22** [comment]
Still an issue, if I lose internet or put my computer to sleep, beekeeper is unusable until I manually disconnect & reconnect (which also takes a few clicks).

**Comment by nakarimi** [comment]
I'm connecting to VM mysql database, I need to refresh the vm, change the snapshot to another one. And beekeeper doesn't detect connection lost, even there is not refresh connection, needs to disconnect, and connect again. 

If there be a refresh button, or refreshing automatically for lost connection to connect again would be great. 

My main reason to use beekeeper is to reduce clicking, like in phpmyadmin, I need to click on pages to find the table that I need, beekeeper resolved it with great search and listing all tables, but this reconnecting each time make it again same, unnecessary clicks that just bothering instead of focusing. 

And it is worse when you forgot that its a connection issue, or a table is empty. 

<img width="999" height="748" alt="Image" src="https://github.com/user-attachments/assets/c084c36b-1d5b-42ca-b99a-03429c646b3c" />
