### ISSUE TITLE
BUG: Issue when opening SQLite databae

### ISSUE THREAD

**Issue by PredellaN** [beekeeper-studio/beekeeper-studio#463]
**Describe the bug**
When opening a specific SQLite db file, no tables/views/triggers are detected. they are detected correctly by DB browser for SQLite and Sqlite expert

**To Reproduce**
1. Open invoiceData.db as SQLite database with Beekeeper
2. See error: no content is displayed

**Expected behavior**
The file content to be correctly visible: tables, views and triggers.

**Version Information (please complete the following information):**
 - OS: Windows and Ubuntu (tried on both)
 - Version 1.8.11

[invoiceData.zip](https://github.com/beekeeper-studio/beekeeper-studio/files/5642394/invoiceData.zip)

**Comment by jackhadrill** [comment]
I'm observing this same behaviour.

**Comment by rathboma** [comment]
Thanks for sharing the file. I'll take a look and see.

**Comment by qfwwfq** [comment]
Hello. Any news? Same problem here, just now.

**Comment by qfwwfq** [comment]
[beekeeper.log](https://github.com/beekeeper-studio/beekeeper-studio/files/8405644/beekeeper.log)
I attach the debug log. 


Moreover, this is the contnt of renderer.log


[2022-04-03 19:22:54.728] [error]                       unable to parse connection string, assuming sqlite file URIError: URI malformed
    at decodeURIComponent (<anonymous>)
    at s (app://./js/chunk-vendors.d02b6115.js:2441:118374)
    at Object.c [as parseHost] (app://./js/chunk-vendors.d02b6115.js:2441:119130)
    at app://./js/chunk-vendors.d02b6115.js:54:22340
    at Array.forEach (<anonymous>)
    at new e (app://./js/chunk-vendors.d02b6115.js:54:22311)
    at nb.parse (app://./js/app.84baa19d.js:1:345413)
    at b.openUrl (app://./js/app.84baa19d.js:1:423071)
    at Array.<anonymous> (app://./js/chunk-vendors.d02b6115.js:2433:6511)
    at b.dispatch (app://./js/chunk-vendors.d02b6115.js:2433:7846)

**Comment by not-night-but** [comment]
@PredellaN I just test this with your attached database and I can't seem to reproduce the issue, though it may have been fixed by upgrading our sqlite lib.

@qfwwfq Are you still seeing this behaviour?

**Comment by nexblu** [comment]
> @PredellaN I just test this with your attached database and I can't seem to reproduce the issue, though it may have been fixed by upgrading our sqlite lib.
> 
> @qfwwfq Are you still seeing this behaviour?

I still have the same error, can't open the db file

**Comment by qfwwfq** [comment]
Hi .
I have just seen your email. I could not answer your questions, because,
when I faced the problem and could not open the database, I switched to
another client. Moreover, I do not think I have the database where the
problem showed now and do not have the same environment (OS, drivers,  etc).

**Comment by exequiel-gualtieri** [comment]
Hi.
I hope this works.
I had a similar problem after updating my beekeeper. So I thought about reinstalling it. Now it is working again.
