### ISSUE TITLE
UnhandledRejection DriverPackageNotInstalledError: SQLite package has not been found installed (AppImage/.deb @ Ubuntu 18.04)

### ISSUE THREAD

**Issue by David-Lor** [beekeeper-studio/beekeeper-studio#466]
**Describe the bug**

When trying to run the app, this is returned:

```
$ ./Beekeeper-Studio-1.8.11.AppImage 
12:34:39.191                  › initializing background
12:34:39.195                  › initializing user ORM connection
12:34:39.195                  › registering schema
Gtk-Message: 12:34:39.259: Failed to load module "unity-gtk-module"
Gtk-Message: 12:34:39.262: Failed to load module "unity-gtk-module"
12:34:39.330                  › Creating first window
12:34:39.411                  › UnhandledRejection DriverPackageNotInstalledError: SQLite package has not been found installed. Try to install it: npm install sqlite3 --save
    at process.r (/tmp/.mount_BeekeeEZ93yG/resources/app.asar/background.js:2:291089)
    at process.emit (events.js:210:5)
    at processPromiseRejections (internal/process/promises.js:201:33)
    at processTicksAndRejections (internal/process/task_queues.js:94:32)
```

Nothing happens, no window gets opened, but the process never dies.

**Version Information (please complete the following information):**
 - OS: Ubuntu 18.04 x86_64 Linux 4.15.0-124-generic
 - App Version: 1.8.11 (AppImage & .deb package)

**Comment by rathboma** [comment]
Huh. Can you check the deb package? I'm not sure why this would be true on an x64 system

**Comment by rathboma** [comment]
I can't replicate this. I have just created a fresh install of Xubuntu with nothing installed and everything works fine for me.

Did you ever manage to install the deb and have that work?

**Comment by David-Lor** [comment]
@rathboma Sorry for the delay. I installed the deb package and I'm having the same issue, so it's not just a problem with the AppImage:

```
$ "/opt/Beekeeper Studio/beekeeper-studio"
20:20:53.633                  › initializing background
20:20:53.635                  › initializing user ORM connection
20:20:53.635                  › registering schema
Gtk-Message: 20:20:53.688: Failed to load module "unity-gtk-module"
Gtk-Message: 20:20:53.690: Failed to load module "unity-gtk-module"
20:20:53.710                  › Creating first window
20:20:53.748                  › UnhandledRejection DriverPackageNotInstalledError: SQLite package has not been found installed. Try to install it: npm install sqlite3 --save
    at process.r (/opt/Beekeeper Studio/resources/app.asar/background.js:2:291089)
    at process.emit (events.js:210:5)
    at processPromiseRejections (internal/process/promises.js:201:33)
    at processTicksAndRejections (internal/process/task_queues.js:94:32)
```

I tried the AppImage on another machine with `OS: Debian 10 buster | Kernel: x86_64 Linux 4.19.0-12-amd64` and it worked fine there.

**Comment by rathboma** [comment]
Very strange. I haven't seen other reports of this and the app is built on 18.04..

Can you run with debug and send me the logs?

`DEBUG=* beekeeper-studio`

**Comment by David-Lor** [comment]
Sure thing. Here is the output when running the appimage:

```
$ DEBUG=* ./Beekeeper-Studio-1.8.11.AppImage 
CLUTTER_IM_MODULE=xim
CONDA_SHLVL=0
LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:
CONDA_EXE=/home/david/.miniconda3/bin/conda
LESSCLOSE=/usr/bin/lesspipe %s %s
XDG_MENU_PREFIX=gnome-
LANG=es_ES.UTF-8
DISPLAY=:1
GNOME_SHELL_SESSION_MODE=ubuntu
APPIMAGE=/home/david/Beekeeper-Studio-1.8.11.AppImage
DEBUG=*
COLORTERM=truecolor
USERNAME=david
JAVA_HOME=/usr/lib/jvm/java-8-oracle
J2SDKDIR=/usr/lib/jvm/java-8-oracle
XDG_VTNR=2
SSH_AUTH_SOCK=/run/user/1000/keyring/ssh
MANDATORY_PATH=/usr/share/gconf/ubuntu.mandatory.path
S_COLORS=auto
_CE_M=
XDG_SESSION_ID=4
DERBY_HOME=/usr/lib/jvm/java-8-oracle/db
USER=david
DESKTOP_SESSION=ubuntu
QT4_IM_MODULE=xim
TEXTDOMAINDIR=/usr/share/locale/
GNOME_TERMINAL_SCREEN=/org/gnome/Terminal/screen/9b648a55_d404_4734_81ee_47c631715648
DEFAULTS_PATH=/usr/share/gconf/ubuntu.default.path
PWD=/home/david
HOME=/home/david
CONDA_PYTHON_EXE=/home/david/.miniconda3/bin/python
TEXTDOMAIN=im-config
J2REDIR=/usr/lib/jvm/java-8-oracle/jre
SSH_AGENT_PID=3984
QT_ACCESSIBILITY=1
XDG_SESSION_TYPE=x11
XDG_DATA_DIRS=/usr/share/ubuntu:/home/david/.local/share/flatpak/exports/share/:/var/lib/flatpak/exports/share/:/usr/local/share/:/usr/share/:/var/lib/snapd/desktop
_CE_CONDA=
XDG_SESSION_DESKTOP=ubuntu
GJS_DEBUG_OUTPUT=stderr
ARGV0=./Beekeeper-Studio-1.8.11.AppImage
GTK_MODULES=gail:atk-bridge
WINDOWPATH=2
VTE_VERSION=5202
SHELL=/bin/bash
TERM=xterm-256color
QT_IM_MODULE=ibus
XMODIFIERS=@im=ibus
IM_CONFIG_PHASE=2
XDG_CURRENT_DESKTOP=ubuntu:GNOME
GPG_AGENT_INFO=/run/user/1000/gnupg/S.gpg-agent:0:1
GNOME_TERMINAL_SERVICE=:1.98
SHLVL=2
XDG_SEAT=seat0
GDMSESSION=ubuntu
APPDIR=/tmp/.mount_Beekeethqf6n
GNOME_DESKTOP_SESSION_ID=this-is-deprecated
LOGNAME=david
DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
XDG_RUNTIME_DIR=/run/user/1000
XAUTHORITY=/run/user/1000/gdm/Xauthority
XDG_CONFIG_DIRS=/etc/xdg/xdg-ubuntu:/etc/xdg
PATH=/home/david/.miniconda3/condabin:/home/david/.miniconda3/bin:/home/david/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin
GJS_DEBUG_TOPICS=JS ERROR;JS LOG
SESSION_MANAGER=local/Ubuntu-Main:@/tmp/.ICE-unix/3902,unix/Ubuntu-Main:/tmp/.ICE-unix/3902
LESSOPEN=| /usr/bin/lesspipe %s
OWD=/home/david
GTK_IM_MODULE=ibus
_=/usr/bin/env
+ THIS=/tmp/.mount_Beekeethqf6n/AppRun
+ args=("$@")
+ NUMBER_OF_ARGS=0
+ '[' -z /tmp/.mount_Beekeethqf6n ']'
+ export PATH=/tmp/.mount_Beekeethqf6n:/tmp/.mount_Beekeethqf6n/usr/sbin:/home/david/.miniconda3/condabin:/home/david/.miniconda3/bin:/home/david/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin
+ PATH=/tmp/.mount_Beekeethqf6n:/tmp/.mount_Beekeethqf6n/usr/sbin:/home/david/.miniconda3/condabin:/home/david/.miniconda3/bin:/home/david/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin
+ export XDG_DATA_DIRS=./share/:/usr/share/gnome:/usr/local/share/:/usr/share/:/usr/share/ubuntu:/home/david/.local/share/flatpak/exports/share/:/var/lib/flatpak/exports/share/:/usr/local/share/:/usr/share/:/var/lib/snapd/desktop
+ XDG_DATA_DIRS=./share/:/usr/share/gnome:/usr/local/share/:/usr/share/:/usr/share/ubuntu:/home/david/.local/share/flatpak/exports/share/:/var/lib/flatpak/exports/share/:/usr/local/share/:/usr/share/:/var/lib/snapd/desktop
+ export LD_LIBRARY_PATH=/tmp/.mount_Beekeethqf6n/usr/lib:
+ LD_LIBRARY_PATH=/tmp/.mount_Beekeethqf6n/usr/lib:
+ export XDG_DATA_DIRS=/tmp/.mount_Beekeethqf6n/usr/share/:./share/:/usr/share/gnome:/usr/local/share/:/usr/share/:/usr/share/ubuntu:/home/david/.local/share/flatpak/exports/share/:/var/lib/flatpak/exports/share/:/usr/local/share/:/usr/share/:/var/lib/snapd/desktop:/usr/share/gnome/:/usr/local/share/:/usr/share/
+ XDG_DATA_DIRS=/tmp/.mount_Beekeethqf6n/usr/share/:./share/:/usr/share/gnome:/usr/local/share/:/usr/share/:/usr/share/ubuntu:/home/david/.local/share/flatpak/exports/share/:/var/lib/flatpak/exports/share/:/usr/local/share/:/usr/share/:/var/lib/snapd/desktop:/usr/share/gnome/:/usr/local/share/:/usr/share/
+ export GSETTINGS_SCHEMA_DIR=/tmp/.mount_Beekeethqf6n/usr/share/glib-2.0/schemas:
+ GSETTINGS_SCHEMA_DIR=/tmp/.mount_Beekeethqf6n/usr/share/glib-2.0/schemas:
+ BIN=/tmp/.mount_Beekeethqf6n/beekeeper-studio
+ '[' -z '' ']'
+ trap atexit EXIT
+ isEulaAccepted=1
+ '[' -z /home/david/Beekeeper-Studio-1.8.11.AppImage ']'
+ atexit
+ '[' 1 == 1 ']'
+ '[' 0 -eq 0 ']'
+ exec /tmp/.mount_Beekeethqf6n/beekeeper-studio
21:07:28.801                  › initializing background
21:07:28.805                  › initializing user ORM connection
21:07:28.805                  › registering schema
Gtk-Message: 21:07:28.872: Failed to load module "unity-gtk-module"
Gtk-Message: 21:07:28.875: Failed to load module "unity-gtk-module"
21:07:28.949                  › Creating first window
21:07:29.034                  › UnhandledRejection DriverPackageNotInstalledError: SQLite package has not been found installed. Try to install it: npm install sqlite3 --save
    at process.r (/tmp/.mount_Beekeethqf6n/resources/app.asar/background.js:2:291089)
    at process.emit (events.js:210:5)
    at processPromiseRejections (internal/process/promises.js:201:33)
    at processTicksAndRejections (internal/process/task_queues.js:94:32)
```

For the installed .deb, no additional debug output is given when running `DEBUG=* /opt/Beekeeper\ Studio/beekeeper-studio`. `beekeeper-studio` is not found.

**Comment by huned** [comment]
I'm also having this problem on ElementaryOS 5.1.7 (based on Ubuntu 18.04). deb, AppImage, and `yarn run electron:serve` all exhibit the same problem:

```bash
 DONE  Compiled successfully in 26100ms                                   9:54:23 PM

No type errors found
Version: typescript 3.9.7
Time: 9535ms

  App running at:
  - Local:   http://localhost:8080/ 
  - Network: http://10.0.1.105:8080/

  Note that the development build is not optimized.
  To create a production build, run yarn build.

⠋  Bundling main process...[BABEL] Note: The code generator has deoptimised the styling of /home/huned/work/forks/beekeeper-studio/node_modules/lodash/lodash.js as it exceeds the max of 500KB.
⠇  Bundling main process...

 DONE  Compiled successfully in 14329ms                                   9:54:38 PM

  File                      Size                       Gzipped

  dist_electron/index.js    3491.05 KiB                633.24 KiB

  Images and other types of assets omitted.

 INFO  Launching Electron...
db-connection
21:54:39.972                  › initializing background
21:54:39.976                  › initializing user ORM connection
21:54:39.976                  › registering schema
installing vue devtools
(node:13237) ExtensionLoadWarning: Warnings loading extension at /home/huned/.config/beekeeper-studio/extensions/nhdogjmejiglipccpnnnanhbledajbpd:
  Unrecognized manifest key 'browser_action'.
  Unrecognized manifest key 'update_url'.
  Permission 'contextMenus' is unknown or URL pattern is malformed.
  Cannot load extension with file or directory name _metadata. Filenames starting with "_" are reserved for use by the system.
(Use `electron --trace-warnings ...` to show where the warning was created)
21:54:40.196                  › Creating first window
21:54:40.206                  › UnhandledRejection DriverPackageNotInstalledError: SQLite package has not been found installed. Try to install it: npm install better-sqlite3 --save
    at process.onRejection (webpack:///./node_modules/electron-log/src/catchErrors.js?:67:18)
    at process.emit (events.js:315:20)
    at processPromiseRejections (internal/process/promises.js:245:33)
    at processTicksAndRejections (internal/process/task_queues.js:94:32)
^C
```

I have a dev env... how can I help debug? Now that I've used beekeeper studio, I just can't go back to the ugly sql clients 😅

**Comment by rathboma** [comment]
This is an issue with `better-sqlite3` being built on Ubuntu 20.04 and thus GLIBC 2.29, rather than <= 2.25 as is in 18.04 and Buster. I'm trying to figure out how to build it from source.

**Comment by huned** [comment]
> This is an issue with `better-sqlite3` being built on Ubuntu 20.04 and thus GLIBC 2.29, rather than <= 2.25 as is in 18.04 and Buster. I'm trying to figure out how to build it from source.

Great sleuthing! 🤞🏾

**Comment by huned** [comment]
Confirmed working in v1.11.6 on ElementaryOS 5.1.7 - amazing work, @rathboma
