### ISSUE TITLE
filtering not working 

### ISSUE THREAD

**Issue by tomjefferson** [beekeeper-studio/beekeeper-studio#515]
the filtering feature not work on win 10 installation. https://prnt.sc/wnbibe 
consider as my database is postgres

**Comment by rathboma** [comment]
@tomjefferson Are there any errors in the console (help -> toggle dev console) or in the log file?

Log file is here: https://docs.beekeeperstudio.io/troubleshooting/#enable-debug-mode-and-collect-logs

**Comment by tomjefferson** [comment]
the log file content 

[2021-01-01 15:03:09.007] [info]                  initializing background
[2021-01-01 15:03:09.172] [info]                  initializing user ORM connection
[2021-01-01 15:03:09.188] [info]                  registering schema
[2021-01-01 15:03:09.264] [info]                  Creating first window
[2021-01-01 15:03:09.889] [info]                  running migrations
[2021-01-01 15:03:19.378] [info]                  getting settings
[2021-01-01 15:03:19.405] [info]                  setting up the menu
[2021-01-01 15:03:19.416] [info]                  Building the window
[2021-01-01 15:03:19.490] [info]                  managing updates
[2021-01-01 15:03:19.501] [info] (update-manager) Not running in AppImageLauncher
[2021-01-01 15:03:23.553] [info] (update-manager) checking for updates right now
[2021-01-01 15:03:23.561] [info] (update-manager) Checking for update
[2021-01-01 15:03:23.597] [info] (update-manager) Generated new staging user ID: e6204fc1-7143-5c80-96af-de404b6074b6
[2021-01-01 15:03:48.275] [error] (update-manager) Error: Error: net::ERR_CONNECTION_CLOSED
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:2568:21)
    at SimpleURLLoaderWrapper.emit (events.js:210:5)
[2021-01-01 15:03:48.309] [error]                  Error: net::ERR_CONNECTION_CLOSED
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:2568:21)
    at SimpleURLLoaderWrapper.emit (events.js:210:5)
[2021-01-04 15:24:59.995] [info]                  initializing background
[2021-01-04 15:25:00.026] [info]                  initializing user ORM connection
[2021-01-04 15:25:00.034] [info]                  registering schema
[2021-01-04 15:25:00.154] [info]                  Creating first window
[2021-01-04 15:25:00.883] [info]                  running migrations
[2021-01-04 15:25:00.941] [info]                  getting settings
[2021-01-04 15:25:00.967] [info]                  setting up the menu
[2021-01-04 15:25:00.979] [info]                  Building the window
[2021-01-04 15:25:01.488] [info]                  managing updates
[2021-01-04 15:25:01.531] [info] (update-manager) Not running in AppImageLauncher
[2021-01-04 15:25:04.785] [info] (update-manager) checking for updates right now
[2021-01-04 15:25:04.794] [info] (update-manager) Checking for update
[2021-01-04 15:25:31.114] [error] (update-manager) Error: Error: net::ERR_CONNECTION_CLOSED
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:2568:21)
    at SimpleURLLoaderWrapper.emit (events.js:210:5)
[2021-01-04 15:25:31.139] [error]                  Error: net::ERR_CONNECTION_CLOSED
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:2568:21)
    at SimpleURLLoaderWrapper.emit (events.js:210:5)
[2021-01-05 11:34:12.292] [info]                  initializing background
[2021-01-05 11:34:12.381] [info]                  initializing user ORM connection
[2021-01-05 11:34:12.403] [info]                  registering schema
[2021-01-05 11:34:12.527] [info]                  Creating first window
[2021-01-05 11:34:12.891] [info]                  running migrations
[2021-01-05 11:34:12.908] [info]                  getting settings
[2021-01-05 11:34:12.924] [info]                  setting up the menu
[2021-01-05 11:34:12.932] [info]                  Building the window
[2021-01-05 11:34:13.004] [info]                  managing updates
[2021-01-05 11:34:13.016] [info] (update-manager) Not running in AppImageLauncher
[2021-01-05 11:34:16.070] [info] (update-manager) checking for updates right now
[2021-01-05 11:34:16.078] [info] (update-manager) Checking for update
[2021-01-05 11:34:47.860] [error] (update-manager) Error: Error: net::ERR_TIMED_OUT
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:2568:21)
    at SimpleURLLoaderWrapper.emit (events.js:210:5)
[2021-01-05 11:34:47.897] [error]                  Error: net::ERR_TIMED_OUT
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:2568:21)
    at SimpleURLLoaderWrapper.emit (events.js:210:5)
[2021-01-05 14:20:15.622] [info]                  initializing background
[2021-01-05 14:20:15.664] [info]                  initializing user ORM connection
[2021-01-05 14:20:15.671] [info]                  registering schema
[2021-01-05 14:20:15.728] [info]                  Creating first window
[2021-01-05 14:20:16.318] [info]                  running migrations
[2021-01-05 14:20:16.340] [info]                  getting settings
[2021-01-05 14:20:16.368] [info]                  setting up the menu
[2021-01-05 14:20:16.379] [info]                  Building the window
[2021-01-05 14:20:16.489] [info]                  managing updates
[2021-01-05 14:20:16.501] [info] (update-manager) Not running in AppImageLauncher
[2021-01-05 14:20:19.586] [info] (update-manager) checking for updates right now
[2021-01-05 14:20:19.595] [info] (update-manager) Checking for update
[2021-01-05 14:20:45.327] [error] (update-manager) Error: Error: net::ERR_CONNECTION_CLOSED
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:2568:21)
    at SimpleURLLoaderWrapper.emit (events.js:210:5)
[2021-01-05 14:20:45.351] [error]                  Error: net::ERR_CONNECTION_CLOSED
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:2568:21)
    at SimpleURLLoaderWrapper.emit (events.js:210:5)
[2021-01-06 09:40:15.395] [info]                  initializing background
[2021-01-06 09:40:15.449] [info]                  initializing user ORM connection
[2021-01-06 09:40:15.471] [info]                  registering schema
[2021-01-06 09:40:15.607] [info]                  Creating first window
[2021-01-06 09:40:16.458] [info]                  running migrations
[2021-01-06 09:40:16.479] [info]                  getting settings
[2021-01-06 09:40:16.495] [info]                  setting up the menu
[2021-01-06 09:40:16.503] [info]                  Building the window
[2021-01-06 09:40:16.574] [info]                  managing updates
[2021-01-06 09:40:16.586] [info] (update-manager) Not running in AppImageLauncher
[2021-01-06 09:40:19.598] [info] (update-manager) checking for updates right now
[2021-01-06 09:40:19.606] [info] (update-manager) Checking for update
[2021-01-06 09:40:45.163] [error] (update-manager) Error: Error: net::ERR_CONNECTION_CLOSED
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:2568:21)
    at SimpleURLLoaderWrapper.emit (events.js:210:5)
[2021-01-06 09:40:45.187] [error]                  Error: net::ERR_CONNECTION_CLOSED
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:2568:21)
    at SimpleURLLoaderWrapper.emit (events.js:210:5)
[2021-01-06 22:29:33.312] [info]                  initializing background
[2021-01-06 22:29:33.368] [info]                  initializing user ORM connection
[2021-01-06 22:29:33.386] [info]                  registering schema
[2021-01-06 22:29:33.445] [info]                  Creating first window
[2021-01-06 22:29:34.236] [info]                  running migrations
[2021-01-06 22:29:34.262] [info]                  getting settings
[2021-01-06 22:29:34.281] [info]                  setting up the menu
[2021-01-06 22:29:34.294] [info]                  Building the window
[2021-01-06 22:29:34.416] [info]                  managing updates
[2021-01-06 22:29:34.428] [info] (update-manager) Not running in AppImageLauncher
[2021-01-06 22:29:37.388] [info] (update-manager) checking for updates right now
[2021-01-06 22:29:37.396] [info] (update-manager) Checking for update
[2021-01-06 22:30:09.535] [error] (update-manager) Error: Error: net::ERR_TIMED_OUT
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:2568:21)
    at SimpleURLLoaderWrapper.emit (events.js:210:5)
[2021-01-06 22:30:09.568] [error]                  Error: net::ERR_TIMED_OUT
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:2568:21)
    at SimpleURLLoaderWrapper.emit (events.js:210:5)
[2021-01-07 10:22:25.261] [info]                  initializing background
[2021-01-07 10:22:25.297] [info]                  initializing user ORM connection
[2021-01-07 10:22:25.305] [info]                  registering schema
[2021-01-07 10:22:25.359] [info]                  Creating first window
[2021-01-07 10:22:25.816] [info]                  running migrations
[2021-01-07 10:22:25.847] [info]                  getting settings
[2021-01-07 10:22:25.878] [info]                  setting up the menu
[2021-01-07 10:22:25.903] [info]                  Building the window
[2021-01-07 10:22:26.008] [info]                  managing updates
[2021-01-07 10:22:26.020] [info] (update-manager) Not running in AppImageLauncher
[2021-01-07 10:22:28.973] [info] (update-manager) checking for updates right now
[2021-01-07 10:22:28.981] [info] (update-manager) Checking for update
[2021-01-07 10:23:01.151] [error] (update-manager) Error: Error: net::ERR_TIMED_OUT
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:2568:21)
    at SimpleURLLoaderWrapper.emit (events.js:210:5)
[2021-01-07 10:23:01.188] [error]                  Error: net::ERR_TIMED_OUT
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:2568:21)
    at SimpleURLLoaderWrapper.emit (events.js:210:5)
[2021-01-08 22:24:28.467] [info]                  initializing background
[2021-01-08 22:25:10.771] [error] (update-manager) Error: Error: net::ERR_TIMED_OUT
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:2568:21)
    at SimpleURLLoaderWrapper.emit (events.js:210:5)
[2021-01-08 22:25:10.781] [error]                  Error: net::ERR_TIMED_OUT
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:2568:21)
    at SimpleURLLoaderWrapper.emit (events.js:210:5)
[2021-01-11 13:52:51.574] [info]                  initializing background
[2021-01-11 13:53:28.715] [error] (update-manager) Error: Error: net::ERR_TIMED_OUT
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:2568:21)
    at SimpleURLLoaderWrapper.emit (events.js:210:5)
[2021-01-11 13:53:28.739] [error]                  Error: net::ERR_TIMED_OUT
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:2568:21)
    at SimpleURLLoaderWrapper.emit (events.js:210:5)
[2021-01-12 12:06:06.621] [info]                  initializing background
[2021-01-12 12:06:06.719] [info]                  initializing user ORM connection
[2021-01-12 12:06:06.740] [info]                  registering schema
[2021-01-12 12:06:06.834] [info]                  Creating first window
[2021-01-12 12:06:07.247] [info]                  running migrations
[2021-01-12 12:06:07.264] [info]                  getting settings
[2021-01-12 12:06:07.280] [info]                  setting up the menu
[2021-01-12 12:06:07.293] [info]                  Building the window
[2021-01-12 12:06:07.488] [info]                  managing updates
[2021-01-12 12:06:07.541] [info] (update-manager) Not running in AppImageLauncher
[2021-01-12 12:06:10.971] [info] (update-manager) checking for updates right now
[2021-01-12 12:06:10.981] [info] (update-manager) Checking for update
[2021-01-12 12:06:36.047] [error] (update-manager) Error: Error: net::ERR_CONNECTION_CLOSED
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:2568:21)
    at SimpleURLLoaderWrapper.emit (events.js:210:5)
[2021-01-12 12:06:36.090] [error]                  Error: net::ERR_CONNECTION_CLOSED
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:2568:21)
    at SimpleURLLoaderWrapper.emit (events.js:210:5)
[2021-01-14 14:27:35.853] [info]                  initializing background
[2021-01-14 14:27:35.905] [info]                  initializing user ORM connection
[2021-01-14 14:27:35.928] [info]                  registering schema
[2021-01-14 14:27:36.054] [info]                  Creating first window
[2021-01-14 14:27:36.601] [info]                  running migrations
[2021-01-14 14:27:36.618] [info]                  getting settings
[2021-01-14 14:27:36.633] [info]                  setting up the menu
[2021-01-14 14:27:36.647] [info]                  Building the window
[2021-01-14 14:27:36.943] [info]                  managing updates
[2021-01-14 14:27:36.954] [info] (update-manager) Not running in AppImageLauncher
[2021-01-14 14:27:40.491] [info] (update-manager) checking for updates right now
[2021-01-14 14:27:40.501] [info] (update-manager) Checking for update
[2021-01-14 14:28:05.580] [error] (update-manager) Error: Error: net::ERR_CONNECTION_CLOSED
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:2568:21)
    at SimpleURLLoaderWrapper.emit (events.js:210:5)
[2021-01-14 14:28:05.604] [error]                  Error: net::ERR_CONNECTION_CLOSED
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:2568:21)
    at SimpleURLLoaderWrapper.emit (events.js:210:5)
[2021-01-19 16:22:37.631] [info]                  initializing background
[2021-01-19 16:22:37.736] [info]                  initializing user ORM connection
[2021-01-19 16:22:37.761] [info]                  registering schema
[2021-01-19 16:22:37.899] [info]                  Creating first window
[2021-01-19 16:22:38.530] [info]                  running migrations
[2021-01-19 16:22:38.552] [info]                  getting settings
[2021-01-19 16:22:38.573] [info]                  setting up the menu
[2021-01-19 16:22:38.587] [info]                  Building the window
[2021-01-19 16:22:38.920] [info]                  managing updates
[2021-01-19 16:22:38.935] [info] (update-manager) Not running in AppImageLauncher
[2021-01-19 16:22:42.690] [info] (update-manager) checking for updates right now
[2021-01-19 16:22:42.709] [info] (update-manager) Checking for update
[2021-01-19 16:23:08.493] [error] (update-manager) Error: Error: net::ERR_CONNECTION_CLOSED
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:2568:21)
    at SimpleURLLoaderWrapper.emit (events.js:210:5)
[2021-01-19 16:23:08.523] [error]                  Error: net::ERR_CONNECTION_CLOSED
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:2568:21)
    at SimpleURLLoaderWrapper.emit (events.js:210:5)

**Comment by tvarsis** [comment]
I have the same issue with PostgreSQL 12 and on Linux. I have a db with 800 tables, a lot of views/functions etc. Filtering does not work at all/gives random results and/or crashes the application. Should be very easy to replicate if you have a larger db to connect to.

**Comment by LuisEngelniederhammer** [comment]
same/similar issue here. It seems the filtering itself is in fact working, it does show how many entities were found, which in my case is correct
![image](https://user-images.githubusercontent.com/6483329/219603383-2ad4cf74-b881-4b2b-a628-433cd9d95c4d.png)

It just does not display them, it's an empty list.
Tested with postgres 11 and 12

**Comment by juanmvrkemok** [comment]
Same here, when i filter by a function name for example, the number of entities matching the name shows up, but the list itself is empty.
![image](https://user-images.githubusercontent.com/126504908/229160444-25245fe9-6c5f-4add-9adc-7643fca4ee05.png)
