### ISSUE TITLE
 DriverPackageNotInstalledError: SQLite package has not been found installed. Try to install it: npm install sqlite3 --save

### ISSUE THREAD

**Issue by Bill-cmy** [beekeeper-studio/beekeeper-studio#517]
] (node:18040) UnhandledPromiseRejectionWarning: DriverPackageNotInstalledError: SQLite package has not been found installed. Try to install it: npm install sqlite3 --save
[Node]     at new DriverPackageNotInstalledError (D:\新建文档\vue7\day7\01-上课资料\01-上课资料\Typescript-Node-Koa2-master\Typescript-Node-Koa2-master\node_modules\typeorm\error\DriverPackageNotInstalledError.js:10:28)
[Node]     at SqliteDriver.loadDependencies (D:\新建文档\vue7\day7\01-上课资料\01-上课资料\Typescript-Node-Koa2-master\Typescript-Node-Koa2-master\node_modules\typeorm\driver\sqlite\SqliteDriver.js:120:19)
[Node]     at new SqliteDriver (D:\新建文档\vue7\day7\01-上课资料\01-上课资料\Typescript-Node-Koa2-master\Typescript-Node-Koa2-master\node_modules\typeorm\driver\sqlite\SqliteDriver.js:26:15)
[Node]     at DriverFactory.create (D:\新建文档\vue7\day7\01-上课资料\01-上课资料\Typescript-Node-Koa2-master\Typescript-Node-Koa2-master\node_modules\typeorm\driver\DriverFactory.js:38:24)
[Node]     at new Connection (D:\新建文档\vue7\day7\01-上课资料\01-上课资料\Typescript-Node-Koa2-master\Typescript-Node-Koa2-master\node_modules\typeorm\connection\Connection.js:52:59)
[Node]     at ConnectionManager.create (D:\新建文档\vue7\day7\01-上课资料\01-上课资料\Typescript-Node-Koa2-master\Typescript-Node-Koa2-master\node_modules\typeorm\connection\ConnectionManager.js:56:26)
[Node]     at Object.<anonymous> (D:\新建文档\vue7\day7\01-上课资料\01-上课资料\Typescript-Node-Koa2-master\Typescript-Node-Koa2-master\node_modules\typeorm\index.js:201:66)
[Node]     at step (D:\新建文档\vue7\day7\01-上课资料\01-上课资料\Typescript-Node-Koa2-master\Typescript-Node-Koa2-master\node_modules\tslib\tslib.js:136:27)
[Node]     at Object.next (D:\新建文档\vue7\day7\01-上课资料\01-上课资料\Typescript-Node-Koa2-master\Typescript-Node-Koa2-master\node_modules\tslib\tslib.js:117:57)
[Node]     at D:\新建文档\vue7\day7\01-上课资料\01-上课资料\Typescript-Node-Koa2-master\Typescript-Node-Koa2-master\node_modules\tslib\tslib.js:110:75
[Node] (node:18040) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
[Node] (node:18040) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by rathboma** [comment]
Hey!

Is this when you start Beekeeper Studio? These file paths look like a different project?

**Comment by UtechtDustin** [comment]
Duplicate of #466 ?

**Comment by rathboma** [comment]
possibly. Although it looks like they're setting up a KOA api project

**Comment by not-night-but** [comment]
Closing this as stale and possibly fixed along with #466
