### ISSUE TITLE
BUG: Latest AppImage failed to launch

### ISSUE THREAD

**Issue by AlexanderMisel** [beekeeper-studio/beekeeper-studio#663]
**Describe the bug**
```
Fontconfig error: "/home/alexander/.config/fontconfig/fonts.conf", line 1: Extra content at the end of the document

db-connection
22:37:34.434                  › initializing background
22:37:34.786                  › UnhandledRejection DriverPackageNotInstalledError: SQLite package has not been found installed. Try to install it: npm install better-sqlite3 --save
    at process.n (/tmp/.mount_BeekeeyZowvb/resources/app.asar/background.js:2:303632)
    at process.emit (events.js:315:20)
    at processPromiseRejections (internal/process/promises.js:245:33)
    at processTicksAndRejections (internal/process/task_queues.js:94:32)

```

**Version Information (please complete the following information):**
 - OS: Deepin 20
 - App Version 1.11.5

**Comment by rathboma** [comment]
I noticed is also a font config error? Can you move that font config file and then try again to see if it's related?

**Comment by AlexanderMisel** [comment]
fonts.conf is an empty file, I think it's unrelated.  I used version 1.10.2 before. It can launch correctly.

**Comment by rathboma** [comment]
Can you give me some more system information? Are you on an arm machine by any chance?

**Comment by AlexanderMisel** [comment]
Deepin 20.2.1, using the AppImage package
```bash
              ............                alexander@alexander-PC
          .';;;;;.       .,;,.            OS: Deepin 20.2.1
       .,;;;;;;;.       ';;;;;;;.         Kernel: x86_64 Linux 5.10.29-amd64-desktop
     .;::::::::'     .,::;;,''''',.       Uptime: 1d 12h 46m
    ,'.::::::::    .;;'.          ';      Packages: 1711
   ;'  'cccccc,   ,' :: '..        .:     Shell: bash
  ,,    :ccccc.  ;: .c, '' :.       ,;    Resolution: 1366x768
 .l.     cllll' ., .lc  :; .l'       l.   DE: Deepin 20.2.1
 .c       :lllc  ;cl:  .l' .ll.      :'   WM: KWin
 .l        'looc. .   ,o:  'oo'      c,   GTK Theme: deepin [GTK2/3]
 .o.         .:ool::coc'  .ooo'      o.   Icon Theme: bloom
  ::            .....   .;dddo      ;c    CPU: Intel Core i5-3230M @ 4x 3.2GHz
   l:...            .';lddddo.     ,o     GPU: i915drmfb
    lxxxxxdoolllodxxxxxxxxxc      :l      RAM: 5238MiB / 7845MiB
     ,dxxxxxxxxxxxxxxxxxxl.     'o,      
       ,dkkkkkkkkkkkkko;.    .;o;        
         .;okkkkkdl;.    .,cl:.          
             .,:cccccccc:,.              
```

**Comment by konstanzzz** [comment]
same issue on linuxmint lmde 4

```
db-connection
04:10:11.619                  › initializing background
04:10:11.621                  › initializing user ORM connection
04:10:11.621                  › registering schema
04:10:11.669                  › Creating first window
04:10:11.674                  › UnhandledRejection DriverPackageNotInstalledError: SQLite package has not been found installed. Try to install it: npm install better-sqlite3 --save
    at process.n (/opt/Beekeeper Studio/resources/app.asar/background.js:2:303632)
    at process.emit (events.js:315:20)
    at processPromiseRejections (internal/process/promises.js:245:33)
    at processTicksAndRejections (internal/process/task_queues.js:94:32)
```

**Comment by rathboma** [comment]
So this seems to be a problem for distributions based on Debian, rather than Ubuntu.

I'm not super sure what the issue is, as it should package the sqlite sources with the app. I've reproduced the issue in a VM, and I'm investigating now.

**Comment by rathboma** [comment]
Looking into this more, there are other issues with Debian Buster, such as the wrong version of `glibc` being installed. In fact, I can't get Beekeeper Studio to run even in dev mode due to these issues.

I think much of this is new to Electron-12. So I think the Sqlite error is actually a red-herring.

**Comment by rathboma** [comment]
Lucky for you guys we publish a snap version! That's my recommended workaround:

`sudo apt install snapd; sudo snap install beekeeper-studio`

`snap run beekeeper-studio`, or pick from your app menu.

I'm going to close this as we can only afford to test on Ubuntu & Fedora, I don't know if I'll ever be able to fully test on buster.

**Comment by rathboma** [comment]
I think I've fixed it by downgrading a package. Can you test with the ubuntu artifact here - https://github.com/beekeeper-studio/beekeeper-studio/actions/runs/875473732
