### ISSUE TITLE
QUESTION: Generate DDL

### ISSUE THREAD

**Issue by bonniecaruso** [beekeeper-studio/beekeeper-studio#868]
**Details:**
Hi, I am looking for a way to generate a create table script off of an existing table within the application.  This is a feature of other tools I've used, where I can select the table and view the SQL Source (SQL Workbench) or Generate a DDL file (DataGrip).  I thought the "SQL: Create" option under the menu that pops up when you right-click on a table might generate the script but nothing happens when I use it.  Is this currently possible?

**Version Information [might be relevant to your issue]**
Operating System: Mac
App Version 2.1.5 (2.1.5)

**Screenshot / GIF [if appropriate]**:

**Comment by rathboma** [comment]
That should give you the table-create statement. Can you try opening the console and seeing if there's an error? Help -> Show developer console.

Other questions:
- What database type and version are you using? (eg mysql version xx.xx.x)
- Can you take a screenshot of the table in the sidebar?
- Is there anything else you can do to help me replicate this?

**Comment by bonniecaruso** [comment]
Hi, I'm using beekeeper to connect to an Amazon RedShift data warehouse environment for query purposes.  I also have connections to MySQL databases and am unable to utilize the feature in all of them.  Not sure it will help but here's the screenshot you requested.  When I click SQL: Create, the following message appears (accessed via the dev tools):  

Here's the error message that comes up when I attempt to use the feature (accessed via dev tools):
error:  syntax error at or near "SELECT"	vue.runtime.esm.js:1897 error: syntax error at or near "SELECT"
    at h.parseErrorMessage (app://./js/chunk-vendors.eea4ee0e.js:99:18302)
    at handlePacket (app://./js/chunk-vendors.eea4ee0e.js:99:14942)
    at h.parse (app://./js/chunk-vendors.eea4ee0e.js:99:13588)
    at Socket.<anonymous> (app://./js/chunk-vendors.eea4ee0e.js:117:108721)
    at Socket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)

Hope this helps!
![image](https://user-images.githubusercontent.com/29439949/141994214-2c449131-1e93-4133-8cb8-5ed972c1d59d.png)

**Comment by AbdelmounaimK** [comment]
Hello, i have the same problem for a redshift connection. Can someone help us?

**Comment by bigdatamark** [comment]
The problem is that the SQL currently being used in the code for getting the field types and generating a "CREATE TABLE" DDL script is postgresql specific. They'll need to rewrite the query to work on postgresql and redshift, or have a separate client script for redshift.

In getTableCreateScript() in /apps/studio/src/lib/db/clients/postgresql.ts.

Specifically, it's complaining about the LATERAL keyword after SELECT, because lateral joins aren't a thing in Redshift. However, redshift also doesn't support escape string constants or array types.

**Comment by KazimirPodolski** [comment]
"SQL Create" still doesn't work even for trivial table. It seems postgres `text` column with default value `''` breaks it.
