### ISSUE TITLE
BUG: Say something here

### ISSUE THREAD

**Issue by maxmarscaramella** [beekeeper-studio/beekeeper-studio#876]
Starting the program under Raspberry PI OS (bullseye) on Pi 4 (4gb RAM) fails with this error message being shown:

02:21:53.494                  › UnhandledRejection DriverPackageNotInstalledError: SQLite package has not been found installed. Try to install it: npm install sqlite3 --save
    at process.r (/snap/beekeeper-studio/59/resources/app.asar/background.js:2:291089)
    at process.emit (events.js:210:5)
    at processPromiseRejections (internal/process/promises.js:201:33)
    at processTicksAndRejections (internal/process/task_queues.js:94:32)

Thank you for any advice. :)

**Comment by rathboma** [comment]
Is this a 64bit version ofthe raspberry PI os, or the 32bit version? I think the 64bit version should work great, but the 32bit OS is a real pain to maintain and keeps breaking.

**Comment by maxmarscaramella** [comment]
..It's the 32bit version. At the moment this is the version that's prominently advertised on the company site so it's what most of us download actually. :-/
