### ISSUE TITLE
BUG: no tables/views on left sidebar Postgres with external IP

### ISSUE THREAD

**Issue by juhallyn** [beekeeper-studio/beekeeper-studio#965]
**Describe the bug**
Same as issue #802 but on Postgres 9

**To Reproduce**
Load Postgres DB by external ip (work fine with Same db in Local)
connexion works, sql query too but no tables/views on left sidebar

**Expected behavior**
See tables/views ect on left sidebar

**Version Information (please complete the following information):**
 - OS: Linux (Debian 10.10)
 - App Version : 3.0.7
  
**Additional context**
- Same problem with SSH Tunel

```bash
19:21:00.465 (postgresql)        › RUNNING 
SELECT
      schemaname as schema,
      matviewname as name
    FROM pg_matviews
    
    order by schemaname, matviewname;
 null

19:21:01.096 (query-editor)      › error: relation "pg_matviews" does not exist
    at h.parseErrorMessage (app://./js/chunk-vendors.eea4ee0e.js:99:18302)
    at handlePacket (app://./js/chunk-vendors.eea4ee0e.js:99:14942)
    at h.parse (app://./js/chunk-vendors.eea4ee0e.js:99:13588)
    at TLSSocket.<anonymous> (app://./js/chunk-vendors.eea4ee0e.js:117:108721)
    at TLSSocket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at TLSSocket.Readable.push (internal/streams/readable.js:223:10)
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:188:23)

```

**Comment by rathboma** [comment]
Hey! Looks like you're on a pretty old version of postgres - `pg_matviews` was introduced in 9.3 which was released in 2013.

That said I'm adding a fix to just return an empty list if listing materialized views fails. So next version you should see this fixed.
