### ISSUE TITLE
BUG: Missing glyphs in secondary windows

### ISSUE THREAD

**Issue by BitPatty** [beekeeper-studio/beekeeper-studio#986]
**Describe the bug**
On secondary windows set the glyphs don't appear to load, such as the export or about window. This works fine on other electron apps but with beekeeper things are corrupted.

**To Reproduce**
1. Open Beekeeper > About

**Expected behavior**
Glyphs should be loading.

**Screenshots / Gifs**

![image](https://user-images.githubusercontent.com/11077852/150240676-1817e2db-faac-40e5-8815-cf2a3c6a6b5f.png)

![image](https://user-images.githubusercontent.com/11077852/150240930-c104b8d1-6755-4fff-9260-3a989e5868fe.png)

**Version Information (please complete the following information):**
 - OS: Fedora 35 / KDE Plasma 5.23.3 (happens on both X11 and Wayland)
 - App Version:  3.0.11 (snap)

**Additional context**
Unsure if related:

```
...
[more of that above]
Failed to read /snap/beekeeper-studio/134/resources/app.asar/node_modules/typeorm/query-builder/ReturningResultsEntityUpdator.js.map on app protocol Error: Invalid package /snap/beekeeper-studio/134/resources/app.asar/snap/beekeeper-studio/134/resources/app.asar
    at createError (electron/js2c/asar_bundle.js:5:1585)
    at fsReadFileAsar (electron/js2c/asar_bundle.js:5:7370)
    at e.readFile (electron/js2c/asar_bundle.js:5:8550)
    at Function.<anonymous> (/snap/beekeeper-studio/134/resources/app.asar/background.js:2:557329)
Failed to read /snap/beekeeper-studio/134/resources/app.asar/node_modules/typeorm/query-builder/UpdateQueryBuilder.js.map on app protocol Error: Invalid package /snap/beekeeper-studio/134/resources/app.asar/snap/beekeeper-studio/134/resources/app.asar
    at createError (electron/js2c/asar_bundle.js:5:1585)
    at fsReadFileAsar (electron/js2c/asar_bundle.js:5:7370)
    at e.readFile (electron/js2c/asar_bundle.js:5:8550)
    at Function.<anonymous> (/snap/beekeeper-studio/134/resources/app.asar/background.js:2:557329)
Failed to read /snap/beekeeper-studio/134/resources/app.asar/node_modules/typeorm/query-builder/RelationQueryBuilder.js.map on app protocol Error: Invalid package /snap/beekeeper-studio/134/resources/app.asar/snap/beekeeper-studio/134/resources/app.asar
    at createError (electron/js2c/asar_bundle.js:5:1585)
    at fsReadFileAsar (electron/js2c/asar_bundle.js:5:7370)
    at e.readFile (electron/js2c/asar_bundle.js:5:8550)
    at Function.<anonymous> (/snap/beekeeper-studio/134/resources/app.asar/background.js:2:557329)
Failed to read /snap/beekeeper-studio/134/resources/app.asar/node_modules/typeorm/query-builder/RelationUpdater.js.map on app protocol Error: Invalid package /snap/beekeeper-studio/134/resources/app.asar/snap/beekeeper-studio/134/resources/app.asar
    at createError (electron/js2c/asar_bundle.js:5:1585)
    at fsReadFileAsar (electron/js2c/asar_bundle.js:5:7370)
    at e.readFile (electron/js2c/asar_bundle.js:5:8550)
    at Function.<anonymous> (/snap/beekeeper-studio/134/resources/app.asar/background.js:2:557329)
[more of that below]
``` 

```
01:45:37.576                     › initializing background
01:45:37.579                     › initializing user ORM connection
01:45:37.579                     › registering schema
01:45:37.623                     › Parsing app args { _: [], sandbox: false }
01:45:37.655                     › running migrations
running migrations
01:45:37.657                     › getting settings
01:45:37.661                     › setting up the menu
01:45:37.663 (NativeMenuBuilder) › MENUTEMPLATE [
  {
    label: 'File',
    submenu: [
      '[object]',
      '[object]',
      '[object]',
      '[object]',
      '[object]',
      '[object]'
    ]
  },
  {
    label: 'Edit',
    submenu: [
      '[object]',
      '[object]',
      '[object]',
      '[object]',
      '[object]',
      '[object]'
    ]
  },
  {
    label: 'View',
    submenu: [
      '[object]',
      '[object]',
      '[object]',
      '[object]',
      '[object]',
      '[object]',
      '[object]'
    ]
  },
  {
    label: 'Help',
    submenu: [ '[object]', '[object]', '[object]', '[object]' ]
  }
]
01:45:37.666                     › Building the window
01:45:37.666                     › managing updates
01:45:37.667 (update-manager)    › not doing any updates, didn't meet conditional
01:45:37.667 (WindowBuilder)     › constructing the window
01:45:38.964                     › starting logging
01:45:39.266 (StateManager)      › removing from search index 0
01:45:39.266 (StateManager)      › adding to search index 0
```

**Comment by rathboma** [comment]
Hey! Looks like you're using the SNAP version of the app.

This is a known (and annoying) problem with snap that I can't figure out. Here's the best way to work around it:

https://docs.beekeeperstudio.io/troubleshooting/#linux-snap
